import type { Project, ProjectCategory } from "@/lib/types";

/**
 * Every case study on the site.
 *
 * Order here sets the order everywhere: homepage spreads, archive, sitemap and
 * next/prev links. To add a project, append an object and give it the next
 * index. To add a real photograph, drop the file in /public/images and set
 * `src` + `alt` on the matching image brief.
 */

export const projectCategories: ProjectCategory[] = [
  "Technical Leadership",
  "Automation / Motion Systems",
  "Product Development",
  "R&D Testing",
  "Medical / Human-Centered Design",
  "Sustainability",
  "Research",
  "Experimental Design",
];

export const projects: Project[] = [
  /* ==============================================================
     01 — PRECISION OPTICAL POSITIONING FIXTURE
     ============================================================== */
  {
    slug: "precision-optical-positioning-fixture",
    index: "01",
    title: "Precision Optical Positioning Fixture",
    shortTitle: "Optical Fixture",
    organization: "Stryker Endoscopy",
    role: "R&D Mechanical Engineering Co-op",
    timeline: "January 2026 – June 2026",
    status: "Complete",
    theme: "dark",
    categories: [
      "R&D Testing",
      "Experimental Design",
      "Automation / Motion Systems",
      "Medical / Human-Centered Design",
    ],
    projectType: [
      "R&D Engineering",
      "Experimental Design",
      "Precision Motion",
      "Verification + Validation",
      "Medical Devices",
    ],
    cardSummary:
      "An optical positioning bench with four motorized and four manual axes, sub-10-micron, replacing a fully manual setup.",
    summary:
      "Precisely constrains and moves optical devices with respect to a target. Four motorized and four manual axes, sub-10-micron, inside a blackout cage. Replaced a completely manual bench.",
    tools: ["SOLIDWORKS", "Creo", "HALT chamber", "Standard + torsional Instron", "One-off fixtures", "Excel"],
    focus: [],
    specs: [
      { label: "Positioning accuracy", value: "<10 micron" },
      { label: "Motorized axes", value: "4" },
      { label: "Manual axes", value: "4" },
      { label: "Optical control", value: "Complete blackout cage" },
      { label: "Fixture value", value: "≈ $25,000" },
    ],
    hero: {
      id: "stryker-hero",
      orientation: "landscape",
      kind: "cad-render",
      label: "01.0 — GANTRY ASSEMBLY",
      subject: "The gantry assembly with travel annotated on each axis.",
      composition:
        "Wide, low, tightly cropped so the stage stack fills the frame; coordinate triad and axis labels in the lower left; deliberately anonymous hardware.",
      lighting:
        "Near-black ground, single hard key raking across anodized and machined surfaces, deep shadow, no fill — the visual language of an optical bench.",
      purpose:
        "Communicate precision and experimental discipline while showing nothing proprietary.",
      caption: "The gantry assembly, with each axis of travel annotated.",
      status: "final",
      src: "/images/optics-bench-gantry-cad.jpg",
      alt: "CAD assembly of the optical positioning gantry:a vertical tower on a two-axis base stage with an articulated head at the top, travel arrows marking each axis of motion.",
      width: 940,
      height: 1216,
    },
    card: {
      id: "stryker-card",
      orientation: "portrait",
      kind: "photograph",
      label: "01 — PRECISION",
      subject: "The blackout cage open, showing the bench inside.",
      composition: "Extreme close crop, strong diagonal, graduations legible, everything else falling to black.",
      lighting: "Single hard raking key on near-black ground; specular highlight along one machined edge only.",
      purpose: "Give the homepage its one dark, controlled, high-precision note.",
      status: "final",
      src: "/images/optics-bench-cage-open.jpg",
      alt: "The blackout cage with its door open, the scope fixture and target stage visible inside.",
      width: 1500,
      height: 2000,
      caption: "The bench inside its blackout cage.",
    },
    sections: [
            {
        id: "imatest",
        title: "Imatest manual adjustment",
        body: [
          "Purely motorized adjustment risks collision, so a lab jack was incorporated beneath the larger light box.",
          "The light pad kept its functionality, and the offset of the light box was designed in.",
        ],
        media: [
          {
            id: "stryker-g3",
            orientation: "portrait",
            kind: "data",
            label: "01.6 — LIGHT BOX",
            subject: "Light box and lab jack installed.",
            composition: "Square, single chart, thin rules, no gridline clutter, values unlabelled or normalized.",
            lighting: "Flat chart on near-black, pale linework, one blue series.",
            purpose: "Show familiarity with quantitative test interpretation without publishing any real data.",
            caption: "Light box on its lab jack — manual height adjustment, retained to avoid collision risk.",
            status: "final",
            src: "/images/optics-bench-lightbox-installed.jpg",
            alt: "The light box mounted on a lab jack inside the cage, positioned above the target stage.",
            width: 1440,
            height: 1920,
          },
          {
            id: "ob-im1",
            orientation: "panoramic",
            kind: "cad-render",
            label: "01.20 — LIGHT PAD MOUNT",
            subject: "CAD of the light pad mounting under the stage.",
            composition: "As drawn.",
            lighting: "Flat CAD shading.",
            purpose: "Document the design.",
            caption: "The light pad keeps its function, mounted under the stage.",
            status: "final",
            src: "/images/imatest-lightpad-mount.png",
            alt: "CAD view of a slim bracket mounted beneath an aluminium extrusion frame.",
            width: 982,
            height: 352,
          },
          {
            id: "ob-im2",
            orientation: "landscape",
            kind: "cad-render",
            label: "01.21 — STAGE UNDERSIDE",
            subject: "CAD of the stage underside with the drive hardware.",
            composition: "As drawn.",
            lighting: "Flat CAD shading.",
            purpose: "Document the design.",
            caption: "Stage underside: drive hardware and the lab jack mount.",
            status: "final",
            src: "/images/imatest-underside.png",
            alt: "CAD view from below of a frame with a motor and lead screw between the rails.",
            width: 904,
            height: 553,
          },
          {
            id: "ob-im3",
            orientation: "landscape",
            kind: "cad-render",
            label: "01.22 — JACK ARM",
            subject: "CAD of the lab jack support arm.",
            composition: "As drawn.",
            lighting: "Flat CAD shading.",
            purpose: "Document the design.",
            caption: "Support arm for the lab jack, lightened where it could be.",
            status: "final",
            src: "/images/imatest-jack-arm.png",
            alt: "CAD view of a flat machined arm with triangular cutouts and mounting holes.",
            width: 860,
            height: 589,
          },
          {
            id: "ob-im4",
            orientation: "square",
            kind: "cad-render",
            label: "01.23 — ARM PAIR",
            subject: "CAD of the paired support arms.",
            composition: "As drawn.",
            lighting: "Flat CAD shading.",
            purpose: "Document the design.",
            caption: "The arms paired up.",
            status: "final",
            src: "/images/imatest-arm-pair.png",
            alt: "CAD view of two machined arms with lightening cutouts arranged side by side.",
            width: 467,
            height: 507,
          },
          {
            id: "ob-im5",
            orientation: "panoramic",
            kind: "cad-render",
            label: "01.24 — BASE PLATE",
            subject: "CAD of the base plate the jack mounts to.",
            composition: "As drawn.",
            lighting: "Flat CAD shading.",
            purpose: "Document the design.",
            caption: "Base plate for the jack assembly.",
            status: "final",
            src: "/images/imatest-base-plate.png",
            alt: "CAD view of a long flat plate with lightening cutouts and bolt holes.",
            width: 672,
            height: 161,
          },
        ],
      },
      {
        id: "gantry-height",
        title: "Gantry height",
        body: [
          "The original height could not use the full Z-axis range of motion.",
          "The offset was increased to accommodate the Imatest light box.",
        ],
        media: [
          {
            id: "stryker-g6",
            orientation: "landscape",
            kind: "cad-render",
            label: "01.9 — GANTRY HEIGHT",
            subject: "CAD showing the increased gantry offset.",
            composition: "As shot on the bench.",
            lighting: "Available light.",
            purpose: "Document the build and the fixture family as delivered.",
            caption: "Gantry offset increased — the original height could not use the full Z travel.",
            status: "final",
            src: "/images/optics-bench-gantry-height-cad.png",
            alt: "CAD elevation of a gantry tower showing an increased mounting offset above the base.",
            width: 742,
            height: 495,
          },
          {
            id: "ob-gh2",
            orientation: "square",
            kind: "cad-render",
            label: "01.25 — OFFSET DETAIL",
            subject: "CAD detail of the increased mounting offset.",
            composition: "As drawn.",
            lighting: "Flat CAD shading.",
            purpose: "Document the design.",
            caption: "The increased offset, in detail.",
            status: "final",
            src: "/images/gantry-height-detail.png",
            alt: "CAD detail of a bracket raising a tower above its base plate.",
            width: 520,
            height: 475,
          },
        ],
      },
            {
        id: "fixtures",
        title: "Fixtures",
        body: [
          "A machined universal clamp with printed inserts fixtures any size or diameter scope.",
          "A second fixture holds any size flexible scope tip.",
        ],
        media: [
          {
            id: "stryker-g1",
            orientation: "detail",
            kind: "cad-render",
            label: "01.4 — UNIVERSAL CLAMP",
            subject: "Machined universal scope clamp.",
            composition: "Macro crop, single component centered, deep negative space around it.",
            lighting: "Single hard key on near-black, strong specular edge, no fill.",
            purpose: "Carry the precision register of the section visually.",
            status: "final",
            src: "/images/optics-bench-clamp-cad.png",
            alt: "CAD of the machined universal scope clamp, split into two halves around a central bore.",
            width: 671,
            height: 553,
            caption: "The machined universal clamp, which takes printed inserts for each scope diameter.",
          },
          {
            id: "stryker-g2",
            orientation: "detail",
            kind: "diagram",
            label: "01.5 — ALIGNMENT",
            subject: "Dimensioned clamp bore sketch.",
            composition: "Orthographic, generous margins, thin linework, labelled datums and a single beam path across frame.",
            lighting: "Pale steel linework on near-black with the beam path in blue.",
            purpose: "Show the geometric reasoning behind alignment in a way that reveals nothing specific.",
            caption: "Insert geometry: one machined clamp covers the full range of scope diameters.",
            status: "final",
            src: "/images/optics-bench-clamp-sketch.png",
            alt: "Dimensioned sketch of the clamp bore showing the 15 mm and 18 mm diameters the printed inserts span.",
            width: 716,
            height: 542,
          },
          {
            id: "stryker-g4",
            orientation: "portrait",
            kind: "photograph",
            label: "01.7 — CLAMP IN USE",
            subject: "The universal clamp holding a scope on the target stage.",
            composition: "As shot on the bench.",
            lighting: "Available light.",
            purpose: "Document the build and the fixture family as delivered.",
            caption: "The clamp in use, holding a scope on the stage.",
            status: "final",
            src: "/images/optics-bench-clamp-in-use.jpg",
            alt: "A machined clamp mounted on a precision stage gripping the shaft of an endoscope.",
            width: 1500,
            height: 2000,
          },
          {
            id: "stryker-g5",
            orientation: "landscape",
            kind: "cad-render",
            label: "01.8 — FLEXIBLE TIP FIXTURE",
            subject: "CAD of the fixture for holding a flexible scope tip.",
            composition: "As shot on the bench.",
            lighting: "Available light.",
            purpose: "Document the build and the fixture family as delivered.",
            caption: "A second fixture family holds flexible scope tips of any size.",
            status: "final",
            src: "/images/optics-bench-flex-tip-cad.png",
            alt: "CAD view of a low block fixture with a shaped channel for holding a flexible scope tip.",
            width: 680,
            height: 442,
          },
        ],
      },
      {
        id: "cage",
        title: "Blackout cage",
        body: [
          "A blackout cage encloses the bench for complete optical isolation.",
        ],
        media: [
          {
            id: "stryker-cage",
            orientation: "portrait",
            kind: "photograph",
            label: "01.2 — BLACKOUT CAGE",
            subject: "The blackout cage, door open.",
            composition: "Portrait, straight-on, enclosure filling frame, one panel open to show interior depth and light trapping.",
            lighting: "Very low key, faint edge light defining panel seams, interior reading as genuine black.",
            purpose: "Convey experimental control and optical discipline while showing nothing proprietary.",
            caption: "The blackout cage open, with the scope fixture and target stage inside.",
            status: "final",
            src: "/images/optics-bench-cage-open.jpg",
            alt: "The blackout cage with its door open, the scope fixture and target stage visible inside.",
            width: 1500,
            height: 2000,
          },
          {
            id: "stryker-g11",
            orientation: "portrait",
            kind: "photograph",
            label: "01.14 — CAGE CLOSED",
            subject: "The blackout cage closed for a run.",
            composition: "As shot on the bench.",
            lighting: "Available light.",
            purpose: "Document the build and the fixture family as delivered.",
            caption: "Closed for a run — complete optical isolation from ambient light.",
            status: "final",
            src: "/images/optics-bench-cage-closed.jpg",
            alt: "A matte black enclosure with its door closed on a laboratory bench.",
            width: 1500,
            height: 2000,
          },
        ],
      },
{
        id: "tower",
        title: "Tower mounting",
        body: [
          "Tower retention force was too low.",
          "The recession was increased to allow placement of two magnets.",
        ],
        media: [
          {
            id: "stryker-g7",
            orientation: "square",
            kind: "cad-render",
            label: "01.10 — TOWER MOUNTING",
            subject: "CAD of the recessed tower mount with two magnets.",
            composition: "As shot on the bench.",
            lighting: "Available light.",
            purpose: "Document the build and the fixture family as delivered.",
            caption: "Tower retention was too weak; the recess was deepened for a second magnet.",
            status: "final",
            src: "/images/optics-bench-tower-mount-cad.png",
            alt: "CAD detail of a recessed mounting pocket sized for two cylindrical magnets.",
            width: 500,
            height: 489,
          },
        ],
      },
      {
        id: "build",
        title: "Build",
        body: [
          "Machined, printed, assembled and wired in-house.",
        ],
        media: [
          {
            id: "stryker-g8",
            orientation: "portrait",
            kind: "photograph",
            label: "01.11 — MACHINING",
            subject: "Machining a fixture component on the mill.",
            composition: "As shot on the bench.",
            lighting: "Available light.",
            purpose: "Document the build and the fixture family as delivered.",
            caption: "Machining fixture components in-house.",
            status: "final",
            src: "/images/optics-bench-build-mill.jpg",
            alt: "An end mill cutting an aluminium extrusion held in a milling vice.",
            width: 1500,
            height: 2000,
          },
          {
            id: "stryker-g9",
            orientation: "portrait",
            kind: "photograph",
            label: "01.12 — ALIGNMENT",
            subject: "Indicating a part in before machining.",
            composition: "As shot on the bench.",
            lighting: "Available light.",
            purpose: "Document the build and the fixture family as delivered.",
            caption: "Indicating in before cutting — the alignment features had to be right.",
            status: "final",
            src: "/images/optics-bench-build-indicator.jpg",
            alt: "A dial indicator on a magnetic base checking a part clamped in a vice on a surface plate.",
            width: 1500,
            height: 2000,
          },
          {
            id: "stryker-g10",
            orientation: "portrait",
            kind: "photograph",
            label: "01.13 — WIRING",
            subject: "Wiring the controller and motion hardware.",
            composition: "As shot on the bench.",
            lighting: "Available light.",
            purpose: "Document the build and the fixture family as delivered.",
            caption: "Wiring the controller: the build included the electrical side, not just the mechanics.",
            status: "final",
            src: "/images/optics-bench-build-wiring.jpg",
            alt: "Hands soldering a connector at a bench beside an equipment enclosure with terminal blocks.",
            width: 1500,
            height: 2000,
          },
          {
            id: "ob-b4",
            orientation: "detail",
            kind: "photograph",
            label: "01.26 — CUTTING EXTRUSION",
            subject: "Cutting aluminium extrusion to length on the chop saw.",
            composition: "As drawn.",
            lighting: "Flat CAD shading.",
            purpose: "Document the design.",
            caption: "Cutting extrusion to length.",
            status: "final",
            src: "/images/optics-bench-build-chopsaw.jpg",
            alt: "A person cutting an aluminium extrusion on a mitre saw at a workshop bench.",
            width: 2000,
            height: 1500,
          },
        ],
      },
    ],
    gallery: [],
    reflection: [],
    confidentiality: "Proprietary information withheld.",
  },
  {
    slug: "stryker-fixture-designs",
    index: "02",
    title: "Stryker Fixture Designs",
    shortTitle: "Fixture Designs",
    organization: "Stryker Endoscopy",
    role: "R&D Mechanical Engineering Co-op",
    timeline: "January 2026 – June 2026",
    status: "Complete",
    theme: "light",
    categories: [
      "R&D Testing",
      "Experimental Design",
      "Medical / Human-Centered Design",
    ],
    projectType: [
      "R&D Engineering",
      "Design for Test",
      "Mechanical Reliability",
      "Verification + Validation",
      "Medical Devices",
    ],
    cardSummary:
      "Fixtures for laser intensity, interface reliability, focus ring torque and vibration testing.",
    summary:
      "Test fixtures for a camera head, coupler and camera control unit: laser intensity, interface reliability, focus ring torque, and front cover vibration testing.",
    tools: [
      "SOLIDWORKS",
      "Creo",
      "MJF + MJP printing",
      "Instron",
      "Torsional Instron",
      "Vibration table",
      "Manual mill + lathe",
    ],
    focus: [],
    specs: [
      { label: "Print processes", value: "MJF, MJP for alignment-critical features" },
      { label: "Test types", value: "Optical, torque, vibration, lifecycle" },
      { label: "Subsystems", value: "Camera head, coupler, camera control unit" },
    ],
    hero: {
      id: "fixtures-hero",
      orientation: "detail",
      kind: "cad-render",
      label: "02.0 — LASER INTENSITY FIXTURE",
      subject: "The laser intensity fixture, full configuration.",
      composition: "Three-quarter view with the full fixture and its rail in frame.",
      lighting: "Even bench lighting.",
      purpose: "Show the delivered hardware rather than the CAD intent.",
      caption:
        "The laser intensity fixture as built, after five revisions.",
      status: "final",
      src: "/images/thermopile-fixture-cad.png",
      alt: "CAD assembly of the laser intensity fixture in its full configuration, with the source, a scope body and the sensor in line along a rail.",
      width: 875,
      height: 712,
    },
    card: {
      id: "fixtures-card",
      orientation: "detail",
      kind: "cad-render",
      label: "02 — DESIGN FOR TEST",
      subject: "The laser intensity fixture as built.",
      composition: "Isometric, full assembly in frame.",
      lighting: "Flat CAD shading on a pale ground.",
      purpose: "Read as precision test equipment at card size.",
      caption: "Laser intensity fixture, full configuration.",
      status: "final",
      src: "/images/thermopile-fixture-cad.png",
      alt: "CAD assembly of the laser intensity fixture in its full configuration, with the source, a scope body and the sensor in line along a rail.",
      width: 875,
      height: 712,
    },
    sections: [
      {
        id: "laser-intensity",
        title: "Laser intensity fixture",
        body: [
          "A laser intensity testing setup, with and without a scope in the path, at variable distance.",
        ],
        list: [
          "Rev 1 — basic centering, discrete distance markings.",
          "Rev 2 — changed clearances, stronger base.",
          "Rev 3 — added insert system and y-axis lock.",
          "Rev 4 — switched critical alignment features to MJP.",
          "Final — complete locking system, constrained through the coupler instead of the scope, coupler-only version added.",
        ],
        media: [
          {
            id: "fixtures-laser-cad",
            orientation: "square",
            kind: "cad-render",
            label: "02.1 — FINAL REVISION",
            subject: "CAD of the final laser intensity fixture with the locking system.",
            composition: "Isometric on a pale ground.",
            lighting: "Flat CAD shading.",
            purpose: "Show the locking and insert system that ended the revision cycle.",
            caption: "Final revision: complete locking system, constrained through the coupler.",
            status: "final",
            src: "/images/thermopile-fixture-final-cad.png",
            alt: "CAD view of a test fixture with a clamped bore, locking screws and a sliding carriage.",
            width: 554,
            height: 536,
          },
          {
            id: "fixtures-laser-built",
            orientation: "portrait",
            kind: "photograph",
            label: "02.2 — AS BUILT",
            subject: "The assembled fixture in use on the bench.",
            composition: "Close three-quarter view.",
            lighting: "Bench lighting.",
            purpose: "Show the printed inserts and locking hardware in place.",
            caption: "The fixture in use, with printed inserts seated.",
            status: "final",
            src: "/images/thermopile-fixture-built-2.jpg",
            alt: "A printed and machined fixture clamped on a bench rail holding an optical component.",
            width: 1500,
            height: 2000,
          },
          {
            id: "fx-g4",
            orientation: "landscape",
            kind: "cad-render",
            label: "02.13 — LASER FIXTURE ASSEMBLY",
            subject: "CAD of the laser intensity fixture with the sensor in place.",
            composition: "As drawn.",
            lighting: "Flat CAD shading.",
            purpose: "Document the fixture family.",
            caption: "Laser intensity fixture with the sensor mounted.",
            status: "final",
            src: "/images/thermopile-assembly-cad.png",
            alt: "CAD assembly of a test fixture with a sensor head mounted in line with a clamped optical component.",
            width: 921,
            height: 641,
          },
          {
            id: "fx-g5",
            orientation: "landscape",
            kind: "cad-render",
            label: "02.14 — DISTANCE MARKINGS",
            subject: "CAD detail of the discrete distance markings along the rail.",
            composition: "As drawn.",
            lighting: "Flat CAD shading.",
            purpose: "Document the fixture family.",
            caption: "Discrete distance markings along the rail.",
            status: "final",
            src: "/images/thermopile-distance-cad.png",
            alt: "CAD detail of a cylindrical rail with numbered graduation marks along its length.",
            width: 745,
            height: 292,
          },
          {
            id: "fx-full1",
            orientation: "panoramic",
            kind: "cad-render",
            label: "02.19 — FULL VERSION",
            subject: "CAD of the full version with a scope in the optical path.",
            composition: "As drawn.",
            lighting: "Flat CAD shading.",
            purpose: "Document the design.",
            caption: "The full version, with a scope in the optical path.",
            status: "final",
            src: "/images/laser-full-side.png",
            alt: "CAD side view of a long test fixture with a tapered scope body between the source and the sensor.",
            width: 1113,
            height: 444,
          },
          {
            id: "fx-full2",
            orientation: "landscape",
            kind: "cad-render",
            label: "02.20 — FULL VERSION DETAIL",
            subject: "CAD detail of the scope interface on the full version.",
            composition: "As drawn.",
            lighting: "Flat CAD shading.",
            purpose: "Document the design.",
            caption: "Scope interface on the full version.",
            status: "final",
            src: "/images/laser-full-detail.png",
            alt: "CAD detail of a clamped interface between a fixture body and a scope.",
            width: 552,
            height: 366,
          },
        ],
      },
            {
        id: "focus-ring",
        title: "Focus ring fixture",
        body: [
          "A focus ring geometry change meant actuation torque had to be tested across the lifecycle, across different fin styles.",
          "I used this fixture to perform torsional Instron testing and torque gauge testing.",
        ],
        media: [
          {
            id: "fixtures-focus-cad",
            orientation: "square",
            kind: "cad-render",
            label: "02.5 — FIN VARIANTS",
            subject: "CAD of the focus ring fixture with an interchangeable insert.",
            composition: "Isometric on a pale ground.",
            lighting: "Flat CAD shading.",
            purpose: "Show the interchangeable insert approach.",
            caption: "Interchangeable inserts let one setup cover every fin style.",
            status: "final",
            src: "/images/focus-ring-fixture-cad.png",
            alt: "CAD view of a circular fixture with a toothed insert for gripping a focus ring.",
            width: 511,
            height: 520,
          },
          {
            id: "fixtures-focus-built",
            orientation: "portrait",
            kind: "photograph",
            label: "02.6 — TORSIONAL TEST",
            subject: "The focus ring fixture mounted for torque measurement.",
            composition: "Vertical, fixture and drive in frame.",
            lighting: "Bench lighting.",
            purpose: "Show the torque measurement setup.",
            caption: "Mounted for torque measurement across lifecycle.",
            status: "final",
            src: "/images/focus-ring-fixture-built.jpg",
            alt: "A fixture mounted in a torsional test frame gripping a ring-shaped component.",
            width: 1500,
            height: 2000,
          },
          {
            id: "fx-g1",
            orientation: "landscape",
            kind: "cad-render",
            label: "02.10 — PENDULUM FOCUS RING FIXTURE",
            subject: "CAD of the focus ring fixture on the pendulum body.",
            composition: "As drawn.",
            lighting: "Flat CAD shading.",
            purpose: "Document the fixture family.",
            caption: "The pendulum focus ring fixture.",
            status: "final",
            src: "/images/focus-ring-pendulum-cad.png",
            alt: "CAD view of a fixture wrapped around a cylindrical camera head body, gripping the focus ring collar.",
            width: 741,
            height: 384,
          },
          {
            id: "fx-g2",
            orientation: "square",
            kind: "cad-render",
            label: "02.11 — FIN GEOMETRY",
            subject: "CAD of a focus ring collar with its fin profile.",
            composition: "As drawn.",
            lighting: "Flat CAD shading.",
            purpose: "Document the fixture family.",
            caption: "One of the fin styles the torque test had to cover.",
            status: "final",
            src: "/images/focus-ring-collar-cad.png",
            alt: "CAD view of a ring collar with raised fins on its outer face.",
            width: 504,
            height: 523,
          },
          {
            id: "fx-g3",
            orientation: "landscape",
            kind: "diagram",
            label: "02.12 — FIN SKETCH",
            subject: "Dimensioned sketch of the fin profile.",
            composition: "As drawn.",
            lighting: "Flat CAD shading.",
            purpose: "Document the fixture family.",
            caption: "Fin profile, dimensioned.",
            status: "final",
            src: "/images/focus-ring-sketch.png",
            alt: "A dimensioned CAD sketch of a curved fin profile with radii and angles called out.",
            width: 844,
            height: 382,
          },
        ],
      },
{
        id: "interface-reliability",
        title: "Interface mechanical reliability",
        body: [
          "Simulates scope use with a coupler, and fully constrains the next-generation coupler to the test fixture.",
        ],
        media: [
          {
            id: "fixtures-endoclamp-cad",
            orientation: "portrait",
            kind: "photograph",
            label: "02.3 — RETENTION FIXTURE",
            subject: "The retention fixture on the bench with a coupler constrained.",
            composition: "Isometric, full assembly.",
            lighting: "Flat CAD shading.",
            purpose: "Show how the coupler is fully constrained to the rig.",
            caption: "Retention fixture — the coupler is fully constrained to the test rig.",
            status: "final",
            src: "/images/endoclamp-fixture-cad.jpg",
            alt: "A test rig built from extrusion, with a coupler clamped upright beneath a linear actuator on a bench.",
            width: 579,
            height: 738,
          },
          {
            id: "fixtures-endoclamp-built",
            orientation: "portrait",
            kind: "photograph",
            label: "02.4 — ON TEST",
            subject: "The retention fixture set up for a reliability run.",
            composition: "Vertical, fixture and load frame in view.",
            lighting: "Bench lighting.",
            purpose: "Show the fixture in the test configuration.",
            caption: "Set up for a mechanical reliability run.",
            status: "final",
            src: "/images/endoclamp-fixture-built.jpg",
            alt: "A test fixture mounted in a load frame with a coupler clamped in position.",
            width: 1500,
            height: 2000,
          },
          {
            id: "fx-g6",
            orientation: "portrait",
            kind: "cad-render",
            label: "02.15 — CLAMP BODY",
            subject: "CAD of the clamp body that constrains the coupler.",
            composition: "As drawn.",
            lighting: "Flat CAD shading.",
            purpose: "Document the fixture family.",
            caption: "The clamp body, labelled for orientation.",
            status: "final",
            src: "/images/endoclamp-clamp-cad.png",
            alt: "CAD view of a cylindrical clamp body with a tapered collar and a cross-drilled base.",
            width: 396,
            height: 637,
          },
          {
            id: "fx-g7",
            orientation: "portrait",
            kind: "photograph",
            label: "02.16 — PRINTED PARTS",
            subject: "The printed clamp components before assembly.",
            composition: "As drawn.",
            lighting: "Flat CAD shading.",
            purpose: "Document the fixture family.",
            caption: "Printed clamp components, as they came off the machine.",
            status: "final",
            src: "/images/endoclamp-printed-parts.jpg",
            alt: "Two teal 3D-printed conical fixture bodies on a bench before assembly.",
            width: 1500,
            height: 2000,
          },
        ],
      },
      {
        id: "ccu",
        title: "Camera control unit — front cover and vibration",
        body: [
          "Front cover mounting and cable receptacle changes needed cable receptacle backout resilience verified under vibration.",
        ],
        media: [
          {
            id: "fixtures-ccu-cad",
            orientation: "wide",
            kind: "cad-render",
            label: "02.7 — FRONT COVER",
            subject: "CAD of the revised front cover mounting and cable receptacle.",
            composition: "Front elevation.",
            lighting: "Flat CAD shading.",
            purpose: "Show the mounting change that required verification.",
            caption: "Revised front cover mounting and cable receptacle.",
            status: "final",
            src: "/images/ccu-front-cover-cad.png",
            alt: "CAD front elevation of a rack-style enclosure cover with connector openings.",
            width: 1337,
            height: 721,
            wide: true,
          },
          {
            id: "fixtures-ccu-vibe",
            orientation: "detail",
            kind: "photograph",
            label: "02.8 — VIBRATION SETUP",
            subject: "The unit mounted for vibration testing.",
            composition: "Three-quarter view of the table and mounted unit.",
            lighting: "Lab lighting.",
            purpose: "Show the vibration test configuration.",
            caption: "Mounted for vibration testing.",
            status: "final",
            src: "/images/ccu-vibration-setup.jpg",
            alt: "An electronics enclosure strapped to a vibration table with instrumentation cables attached.",
            width: 2000,
            height: 1500,
          },
          {
            id: "fx-g9",
            orientation: "landscape",
            kind: "diagram",
            label: "02.18 — RECEPTACLE DETAIL",
            subject: "Dimensioned drawing of the cable receptacle cutout.",
            composition: "As drawn.",
            lighting: "Flat CAD shading.",
            purpose: "Document the fixture family.",
            caption: "Cable receptacle cutout, dimensioned.",
            status: "final",
            src: "/images/ccu-front-cover-drawing.png",
            alt: "An engineering drawing of a rectangular plate with a bolt circle and chamfer callouts.",
            width: 709,
            height: 423,
            wide: true,
          },
        ],
      },
          ],
    gallery: [],
    reflection: [],
    confidentiality: "Proprietary information withheld.",
  },
  {
    slug: "x-ray-scanner-lumafield",
    index: "03",
    title: "X-Ray Scanner for Lumafield",
    shortTitle: "X-Ray Scanner",
    organization: "Generate Product Development Studio / Lumafield project",
    role: "Mechanical Engineering Technical Lead",
    timeline: "Current / In Development",
    status: "In development",
    inDevelopment: true,
    theme: "light",
    categories: [
      "Technical Leadership",
      "Automation / Motion Systems",
      "Product Development",
      "Experimental Design",
    ],
    projectType: [
      "Technical Leadership",
      "Automation",
      "Precision Motion Systems",
      "Industrial Equipment",
      "Radiation-Safety Measurement",
      "Experimental Design",
    ],
    cardSummary:
      "Leading development of a 5-axis, 7 ft × 7 ft × 4 ft gantry system to automate shielding-verification scans around an industrial X-ray CT scanner, targeting 1 mm repeatability.",
    summary:
      "Leading the mechanical development of an automated five-axis gantry system designed to map X-ray emissions around Lumafield Neptune CT scanners with a target of 1 mm repeatability.",
    tools: ["SOLIDWORKS", "Onshape", "FDM + SLA prototyping", "Linear motion components", "Excel"],
    team: "Mechanical, electrical and controls sub-teams at Generate, with Lumafield stakeholders",
    focus: [
      "Motion architecture",
      "Structural stiffness",
      "Repeatability",
      "Measurement coverage",
      "Serviceability",
    ],
    specs: [
      { label: "Gantry envelope", value: "≈ 7 ft × 7 ft × 4 ft" },
      { label: "Motorized axes", value: "5" },
      { label: "Positioning repeatability", value: "1 mm", target: true },
      { label: "Instrument", value: "Thermo Fisher RadEye G20 survey meter" },
      { label: "Subject", value: "Lumafield Neptune industrial X-ray CT scanner" },
      { label: "Scan coverage", value: "Automated paths across multiple scanner faces", target: true },
      { label: "Status", value: "Mechanical design and prototyping in progress" },
    ],
    hero: {
      id: "lumafield-hero",
      orientation: "panoramic",
      kind: "cad-render",
      label: "03.0 — SYSTEM",
      subject:
        "The complete five-axis gantry surrounding the Neptune scanner envelope, with rails, frame members, drive components and the survey-meter end effector visible.",
      composition:
        "Wide, low three-quarter perspective so the frame reads at full height; scanner volume centered in the gantry opening; a human silhouette at frame left for scale; dimension lines marking the 7 ft × 7 ft × 4 ft envelope.",
      lighting:
        "Neutral dark studio or controlled workshop lighting; cool steel and black hardware; single soft key from the upper left; no lens flare or gradient wash.",
      purpose:
        "Establish immediately that this is substantial, real hardware at architectural scale — not a CAD exercise.",
      caption:
        "Automated 5-axis shielding-verification scanner — target: 1 mm repeatability.",
      status: "concept",
    },
    card: {
      id: "lumafield-card",
      orientation: "wide",
      kind: "cad-render",
      label: "03 — GANTRY",
      subject:
        "Three-quarter view of the gantry frame with the scanner envelope in place and one axis mid-travel.",
      composition:
        "Wide crop, horizon low, structure filling the upper two-thirds; leading lines along the top rail.",
      lighting: "Dark neutral background, controlled directional light, restrained blue annotation marks.",
      purpose: "Signal scale and ambition as the first project a visitor sees.",
      status: "concept",
    },
    sections: [
      {
        id: "system",
        title: "System",
        body: [
          "A five-axis gantry, roughly 7 ft × 7 ft × 4 ft, to automate X-ray emission scans around Lumafield Neptune industrial CT scanners.",
          "Target positioning repeatability: 1 mm.",
        ],
        note:
          "This project is a measurement tool. Nothing here suggests that Lumafield scanners are unsafe or inadequately shielded.",
      },
      {
        id: "manual",
        title: "Manual process",
        body: [
          "The scan is currently done by hand, tracing a Thermo Fisher RadEye G20 survey meter across the faces of the scanner.",
        ],
        media: [
          {
            id: "lumafield-manual",
            orientation: "landscape",
            kind: "diagram",
            label: "03.1 — PROCESS",
            subject:
            "Side-by-side comparison graphic: a hand-traced survey path over a scanner face versus a machine-executed raster path over the same face.",
            composition:
            "Two panels sharing one baseline; the manual path drawn as an irregular freehand line, the automated path as a precise raster with consistent pitch and standoff callouts.",
            lighting: "Flat vector artwork on eggshell; steel linework with the automated path in signal blue.",
            purpose:
            "Make the repeatability argument visually in one glance, without implying the manual method is unsafe.",
            caption: "Manual tracing versus a planned automated path.",
            status: "concept",
          },
        ],
      },
      {
        id: "requirements",
        title: "Requirements",
        body: [],
        list: [
          "Reach multiple scanner faces from a fixed frame.",
          "Hold the survey meter at a controlled standoff and orientation.",
          "Target 1 mm positioning repeatability.",
        ],
      },
      {
        id: "architecture",
        title: "Motion architecture",
        body: [
          "Five motorized axes, from the fixed frame to the survey-meter tip.",
        ],
        media: [
          {
            id: "lumafield-axes",
            orientation: "landscape",
            kind: "diagram",
            label: "03.2 — KINEMATICS",
            subject:
            "Technical isometric of the five-axis architecture with each axis labelled, its travel indicated, and the kinematic chain from frame to detector shown in order.",
            composition:
            "Clean isometric line drawing, no shading; travel arrows on each axis; coordinate triad at the origin; detector tip highlighted at the end of the chain.",
            lighting: "Vector linework, steel on eggshell, blue reserved for the active axis arrows.",
            purpose:
            "Let a mechanical reader understand the kinematic chain and where compliance accumulates without reading the body copy.",
            caption: "Five-axis chain from fixed frame to survey-meter tip.",
            status: "concept",
          },
        ],
      },
      {
        id: "end-effector",
        title: "End effector",
        body: [
          "Holds a Thermo Fisher RadEye G20 survey meter, with access for calibration.",
        ],
        media: [
          {
            id: "lumafield-effector",
            orientation: "detail",
            kind: "cad-render",
            label: "03.4 — END EFFECTOR",
            subject:
            "Close-up of the survey-meter mounting interface: instrument cradle, quick-release, cable strain relief and the tool-point offset callout.",
            composition:
            "Tight three-quarter crop filling the frame; shallow depth of field; the instrument body in place to show fit.",
            lighting: "Dark background, single hard key raking across machined and printed surfaces to read texture.",
            purpose:
            "Prove that the interface to a real, unmodifiable instrument was designed deliberately.",
            status: "concept",
          },
        ],
      },
      {
        id: "role",
        title: "Role",
        body: [],
        list: [
          "Own the mechanical architecture and design direction.",
          "Translate the measurement task into functional requirements, motion envelopes, load cases and mechanical interfaces for the electrical and controls sub-teams.",
          "Direct gantry, axis, mechanism, frame and end-effector decisions.",
          "Run iterative design reviews and record the reasoning behind decisions.",
          "Coordinate mechanical work across the project team.",
        ],
      },
      {
        id: "status",
        title: "Status",
        body: [
          "In development. Architecture and envelope are defined; mechanical design of the gantry and end effector, and subsystem prototyping, are in progress.",
          "Figures on this page are design targets. No repeatability, coverage or safety performance has been validated yet.",
        ],
      },
    ],
    gallery: [
      {
        id: "lumafield-g1",
        orientation: "wide",
        kind: "photograph",
        label: "03.6 — SCALE",
        subject: "Wide workshop photograph of the partially assembled frame with a person working inside the envelope.",
        composition: "Eye-level wide shot, person small in frame, top rail crossing the upper third.",
        lighting: "Available workshop light, warm grade, high contrast, no staging.",
        purpose: "Ground the render in the real room the machine has to live in.",
        caption: "Frame assembly in progress. Shown to establish working scale, not final configuration.",
        status: "prototype",
      },
      {
        id: "lumafield-g2",
        orientation: "detail",
        kind: "photograph",
        label: "03.7 — DRIVE",
        subject: "Close-up of a linear rail, carriage, belt or screw drive, motor mount and cable carrier as assembled.",
        composition: "Tight crop along the rail axis, strong diagonal, mechanical texture filling frame.",
        lighting: "Hard raking light on steel and anodized aluminum; dark background.",
        purpose: "Evidence of real hardware selection and assembly, not just modelling.",
        status: "prototype",
      },
      {
        id: "lumafield-g3",
        orientation: "landscape",
        kind: "exploded-view",
        label: "03.8 — ASSEMBLY",
        subject: "Exploded CAD view of one axis: frame member, rail, carriage, drive, motor mount and cable carrier.",
        composition: "Even exploded spacing along one axis, thin leader lines, numbered callouts.",
        lighting: "Neutral studio render on dark ground, matte materials, no reflections competing with the linework.",
        purpose: "Show the part count and assembly logic behind a single axis.",
        status: "concept",
      },
      {
        id: "lumafield-g4",
        orientation: "square",
        kind: "sketch",
        label: "03.9 — CONCEPTS",
        subject: "Notebook page of early gantry configuration sketches with reach and stiffness notes in the margins.",
        composition: "Flat overhead, page filling frame, slight paper texture, pen linework legible.",
        lighting: "Soft diffuse daylight, warm paper tone.",
        purpose: "Show the options considered before the architecture settled.",
        status: "concept",
      },
    ],
    reflection: [],
    confidentiality: "Proprietary information withheld.",
  },
  {
    slug: "sageware-textile-upcycling",
    index: "04",
    title: "Sageware Textile Upcycling System",
    shortTitle: "Sageware",
    organization: "Generate Product Development Studio",
    role: "Mechanical Engineer",
    timeline: "September 2025 – December 2025",
    status: "Complete",
    theme: "light",
    accent: "#6B7F4E",
    categories: [
      "Product Development",
      "Sustainability",
      "Automation / Motion Systems",
    ],
    projectType: [
      "Product Development",
      "Sustainability",
      "Automation / Motion Systems",
      "Tooling",
      "Additive Manufacturing",
    ],
    cardSummary:
      "Designed tooling and fixtures for a compact automated system that converts hard-to-process fabric scraps into jewelry beads.",
    summary:
      "A compact, automated system that upcycles fabric scraps into jewelry beads.",
    tools: ["Onshape", "SLA (high-temperature resin)", "Machined steel inserts", "Shop tools"],
    team: "Generate product-development team",
    focus: ["Tooling design", "Material behavior", "Repeatability", "Compact packaging", "Safe operation"],
    specs: [
      { label: "Input", value: "Mixed fabric scrap, inconsistent weave and thickness" },
      { label: "Output", value: "Formed jewelry beads" },
      { label: "Tooling", value: "Machined sharp steel cutting/stamping inserts" },
      { label: "Fixture", value: "High-temperature SLA resin, machined inserts bonded in" },
      { label: "Packaging", value: "Compact benchtop envelope" },
      { label: "Process", value: "Hardening, cutting/stamping, forming" },
    ],
    hero: {
      id: "sageware-hero",
      orientation: "panoramic",
      kind: "photograph",
      label: "04.0 — SYSTEM",
      subject:
        "The compact benchtop system with fabric scrap at the infeed and finished beads at the outfeed, tooling visible mid-frame.",
      composition:
        "Wide, slightly elevated three-quarter view; process reading left to right; loose scrap and finished beads both in frame.",
      lighting:
        "Warm directional daylight, soft shadow, textile color allowed to carry the frame; light neutral surface.",
      purpose:
        "Set Sageware apart from the industrial work — material-rich, colorful, tactile, product-scale.",
      caption: "Benchtop upcycling system: fabric scrap in, formed beads out.",
      status: "prototype",
    },
    card: {
      id: "sageware-card",
      orientation: "wide",
      kind: "macro",
      label: "04 — MATERIAL",
      subject:
        "Macro of hardened fabric mid-process beside a sharp steel stamping insert, cut edges clearly visible.",
      composition: "Very close crop, fibers and cut edge in sharp focus, insert entering from frame edge.",
      lighting: "Warm raking light to pick up weave, fiber ends and the polish on the steel.",
      purpose: "Lead with material, not machinery — the fabric is the hard part of this project.",
      status: "prototype",
    },
    sections: [
      {
        id: "system",
        title: "System",
        body: [
          "A compact, automated system that upcycles fabric scraps into jewelry beads.",
        ],
      },
      {
        id: "material",
        title: "Material",
        body: [
          "The fabric is hardened first, so it can be cut, stamped and located in a fixture.",
        ],
        media: [
          {
            id: "sageware-macro",
            orientation: "macro",
            kind: "macro",
            label: "04.1 — MATERIAL",
            subject:
            "Macro sequence of the same fabric in three states: raw scrap, hardened blank, finished bead.",
            composition: "Three tight frames at identical scale and angle so the change of state is the only variable.",
            lighting: "Consistent warm side light across all three; shallow depth of field; dark neutral ground.",
            purpose: "Make the central insight of the project legible in one image: change the material state first.",
            caption: "Raw scrap, hardened blank, finished bead.",
            status: "prototype",
          },
        ],
      },
      {
        id: "tooling",
        title: "Tooling and fixture",
        body: [
          "Machined sharp steel inserts cut and stamp the hardened fabric. The fixture body is high-temperature SLA resin, with the inserts seated in it.",
        ],
        media: [
          {
            id: "sageware-insert",
            orientation: "detail",
            kind: "photograph",
            label: "04.2 — TOOLING",
            subject:
            "Close-up of a machined steel cutting/stamping insert seated in the high-temperature SLA fixture body.",
            composition: "Tight three-quarter crop showing the joint between steel and printed resin, edge catching the light.",
            lighting: "Hard raking key on the steel edge, softer fill on the resin so both materials read distinctly.",
            purpose: "Show the hybrid tooling strategy — machined where wear matters, printed where iteration matters.",
            caption: "Machined steel insert in a printed high-temperature fixture body.",
            status: "final",
          },
        ],
      },
      {
        id: "trials",
        title: "Trials",
        body: [
          "Tooling geometry was iterated against a spread of fabric weaves, thicknesses and blends.",
        ],
        media: [
          {
            id: "sageware-iterations",
            orientation: "landscape",
            kind: "prototype",
            label: "04.3 — ITERATION",
            subject: "Lineup of fixture iterations in order, with sample parts produced by each.",
            composition: "Flat overhead, evenly spaced left to right, each fixture paired with its output sample.",
            lighting: "Even soft light, minimal shadow, warm neutral background so resin color reads consistently.",
            purpose: "Make the iteration loop visible and show that the geometry was earned, not guessed.",
            caption: "Fixture revisions with the parts each produced.",
            status: "prototype",
          },
        ],
      },
      {
        id: "constraints",
        title: "Constraints",
        body: [
          "Reliability, compactness and safe operation. Cutting edges are guarded by geometry rather than instruction.",
        ],
      },
    ],
    gallery: [
      {
        id: "sageware-g1",
        orientation: "portrait",
        kind: "photograph",
        label: "04.4 — PROCESS",
        subject: "Hands loading fabric scrap into the fixture during a trial run.",
        composition: "Portrait crop, hands and fixture filling frame, machine context softly out of focus behind.",
        lighting: "Warm window light, honest workshop setting.",
        purpose: "Keep the human scale of a benchtop product visible.",
        status: "prototype",
      },
      {
        id: "sageware-g2",
        orientation: "landscape",
        kind: "exploded-view",
        label: "04.5 — TOOLING CAD",
        subject: "Exploded CAD view of the fixture stack: base, printed body, steel inserts, clamp and retainers.",
        composition: "Vertical explosion along the press axis with thin leader lines and part callouts.",
        lighting: "Clean neutral render, matte materials, steel differentiated from resin by material, not color grading.",
        purpose: "Show the assembly logic and how the inserts are retained and replaced.",
        status: "final",
      },
      {
        id: "sageware-g3",
        orientation: "square",
        kind: "photograph",
        label: "04.6 — OUTPUT",
        subject: "Finished beads arranged to show color and form variation across source fabrics.",
        composition: "Overhead, loose grid, enough beads to read variation without becoming a product-catalog shot.",
        lighting: "Soft warm light, gentle shadow, saturated textile color.",
        purpose: "Close the loop from waste stream to object someone would actually wear.",
        status: "final",
      },
    ],
    reflection: [],
  },
  {
    slug: "uplift-mobility-device",
    index: "05",
    title: "Uplift Mobility Device",
    shortTitle: "Uplift",
    organization: "Generate Product Development Studio",
    role: "Mechanical Engineer",
    timeline: "December 2024 – April 2025",
    status: "Prototype complete",
    theme: "light",
    accent: "#3E5C76",
    categories: [
      "Medical / Human-Centered Design",
      "Product Development",
    ],
    projectType: [
      "Human-Centered Design",
      "Product Development",
      "Mechanisms",
      "Prototyping",
      "Electromechanical Integration",
    ],
    cardSummary:
      "A walker with powered legs and an integrated seat. Conduit linkages, mechanical interfaces and mechanical/electrical integration.",
    summary:
      "An advanced walker with powered legs and an integrated seat, for people with limited mobility.",
    tools: ["Onshape", "FDM (PLA)", "SLA (Grey Pro)", "Shop tools"],
    team: "Mechanical and electrical sub-teams at Generate",
    focus: ["Mechanisms", "Human factors", "Integration", "Weight", "Fast iteration"],
    specs: [
      { label: "Device", value: "Powered walker with integrated seat" },
      { label: "Users", value: "People with limited mobility" },
      { label: "My scope", value: "Conduit linkages, mechanical interfaces, mech/elec integration" },
      { label: "Prototyping", value: "FDM PLA and SLA Grey Pro, iterated in Onshape" },
      { label: "Integration", value: "Motors, electronics housings, battery protection" },
    ],
    hero: {
      id: "uplift-hero",
      orientation: "square",
      kind: "photograph",
      label: "05.0 — DEVICE",
      subject: "The finished walker prototype, seat and powered legs visible.",
      composition: "As shot.",
      lighting: "Available light.",
      purpose: "Show the finished device.",
      caption: "The finished prototype, with powered legs, integrated seat and cable carriers on each side.",
      status: "prototype",
      src: "/images/uplift-showcase.jpg",
      alt: "The white walker prototype on display: aluminium tube frame, printed joints, a black seat, a backrest housing, handles with controls, and cable carriers running down each side to the powered legs.",
      width: 1500,
      height: 1480,
    },
    card: {
      id: "uplift-card",
      orientation: "portrait",
      kind: "cad-render",
      label: "05 — MOBILITY",
      subject: "Full CAD assembly of the walker.",
      composition: "As drawn.",
      lighting: "Flat CAD shading.",
      purpose: "Full CAD assembly: frame, seat, backrest housing, handles and four powered legs.",
      caption: "Full assembly.",
      status: "final",
      src: "/images/uplift-assembly-cad.png",
      alt: "CAD assembly of the walker: tube frame, seat, backrest housing and handles above four powered legs on caster wheels.",
      width: 652,
      height: 737,
    },
    sections: [
      {
        id: "device",
        title: "Device",
        body: [
          "A walker with powered legs and an integrated seat, for people with limited mobility.",
        ],
        media: [
          {
            id: "uplift-assembly",
            orientation: "portrait",
            kind: "cad-render",
            label: "05.1 — ASSEMBLY",
            subject: "Full CAD assembly of the walker.",
            composition: "As drawn.",
            lighting: "Flat CAD shading.",
            purpose: "Document the design.",
            caption: "Full assembly: frame, seat, backrest housing, handles and four powered legs.",
            status: "final",
            src: "/images/uplift-assembly-cad.png",
            alt: "CAD assembly of the walker: tube frame, seat, backrest housing and handles above four powered legs on caster wheels.",
            width: 652,
            height: 737,
          },
        ],
      },
      {
        id: "linkages",
        title: "Conduit linkages",
        body: [
          "I led iterative development of the conduit linkages in Onshape, printed in FDM PLA and SLA Grey Pro.",
        ],
        media: [
          {
            id: "uplift-tee",
            orientation: "landscape",
            kind: "cad-render",
            label: "05.2 — TEE CONDUIT",
            subject: "CAD of a three-way conduit linkage.",
            composition: "As drawn.",
            lighting: "Flat CAD shading.",
            purpose: "Document the design.",
            caption: "Three-way conduit linkage.",
            status: "final",
            src: "/images/uplift-tee-conduit-cad.png",
            alt: "CAD view of a printed three-way tube connector with a vertical socket and two angled branches.",
            width: 833,
            height: 675,
          },
          {
            id: "uplift-elbow",
            orientation: "landscape",
            kind: "cad-render",
            label: "05.3 — ELBOW CONDUIT",
            subject: "CAD of a two-way conduit linkage.",
            composition: "As drawn.",
            lighting: "Flat CAD shading.",
            purpose: "Document the design.",
            caption: "Two-way conduit linkage.",
            status: "final",
            src: "/images/uplift-elbow-conduit-cad.png",
            alt: "CAD view of a printed tube connector joining a vertical socket to an angled branch, with cross-drilled pin holes.",
            width: 667,
            height: 465,
          },
          {
            id: "uplift-leg-mount",
            orientation: "square",
            kind: "cad-render",
            label: "05.4 — LEG MOUNT",
            subject: "CAD of a powered-leg mount.",
            composition: "As drawn.",
            lighting: "Flat CAD shading.",
            purpose: "Document the design.",
            caption: "Powered-leg mount.",
            status: "final",
            src: "/images/uplift-leg-mount-cad.png",
            alt: "CAD view of a cylindrical housing with a three-bolt flange around a central bore.",
            width: 482,
            height: 472,
          },
        ],
      },
      {
        id: "integration",
        title: "Mechanical and electrical integration",
        body: [
          "I coordinated with the electrical sub-team to integrate the motors, house the electronics and protect the battery.",
        ],
        media: [
          {
            id: "uplift-battery-cad",
            orientation: "landscape",
            kind: "cad-render",
            label: "05.5 — BATTERY HOUSING",
            subject: "CAD of the battery housing.",
            composition: "As drawn.",
            lighting: "Flat CAD shading.",
            purpose: "Document the design.",
            caption: "Battery housing.",
            status: "final",
            src: "/images/uplift-battery-housing-cad.png",
            alt: "CAD view of an open rectangular housing with four corner mounting ears and a cable cutout in one end wall.",
            width: 880,
            height: 665,
          },
          {
            id: "uplift-battery-printed",
            orientation: "portrait",
            kind: "photograph",
            label: "05.6 — OFF THE PRINTER",
            subject: "The printed battery housing with supports attached.",
            composition: "As shot.",
            lighting: "Available light.",
            purpose: "Document the build.",
            caption: "The battery housing off the printer, tree supports still attached.",
            status: "final",
            src: "/images/uplift-battery-housing-printed.jpg",
            alt: "A hand holding a white printed housing upside down, its underside covered in branching tree supports.",
            width: 1500,
            height: 2000,
          },
          {
            id: "uplift-battery-built",
            orientation: "portrait",
            kind: "photograph",
            label: "05.7 — BATTERY FITTED",
            subject: "The printed battery housing with the battery seated.",
            composition: "As shot.",
            lighting: "Available light.",
            purpose: "Document the build.",
            caption: "The battery seated in its printed housing.",
            status: "final",
            src: "/images/uplift-battery-housing-built.jpg",
            alt: "A blue battery pack seated in a white printed housing with corner mounting ears, its leads exiting through the end cutout.",
            width: 1500,
            height: 2000,
          },
        ],
      },
    ],
    gallery: [],
    reflection: [],
  },
  {
    slug: "helmet-impact-mechanics",
    index: "06",
    title: "Helmet Impact Mechanics Research",
    shortTitle: "Helmet Impact Research",
    organization:
      "Northeastern University Center for STEM Education / Young Scholars’ Program",
    role: "Research Assistant",
    timeline: "June 2023 – August 2023",
    status: "Published",
    theme: "light",
    accent: "#4A5D6B",
    categories: ["Research", "Experimental Design", "Medical / Human-Centered Design"],
    projectType: [
      "Research",
      "Experimental Mechanics",
      "Biomedical Engineering",
      "Finite Element Analysis",
    ],
    cardSummary:
      "Characterized helmet-padding precompression for impact-mechanics experiments and finite-element analysis; associated research was published in Annals of Biomedical Engineering.",
    summary:
      "Investigated impact mechanics and force propagation in advanced combat helmet systems, with a focus on quantifying padding precompression for finite-element analysis.",
    tools: ["Experimental mechanics", "Compression testing", "Data analysis", "FEA inputs"],
    team: "University research group, Young Scholars’ Program",
    focus: ["Experimental mechanics", "Measurement method", "Model inputs", "Force propagation"],
    specs: [
      { label: "System studied", value: "Advanced combat helmet systems" },
      { label: "Measured quantity", value: "Padding precompression in the fitted state" },
      { label: "Method", value: "Experimental compression characterization" },
      { label: "Application", value: "Inputs and boundary conditions for finite-element analysis" },
      { label: "Publication", value: "Annals of Biomedical Engineering, Vol. 53" },
    ],
    hero: {
      id: "helmet-hero",
      orientation: "panoramic",
      kind: "photograph",
      label: "06.0 — SETUP",
      subject:
        "The experimental setup: helmet system positioned in a compression rig with padding and instrumentation visible.",
      composition:
        "Wide, straight-on or slight three-quarter view of the rig; specimen centered; measurement hardware legible at the edges.",
      lighting:
        "Even neutral lab lighting, moderate contrast, plain background so the apparatus reads clearly.",
      purpose:
        "Establish that the research rested on physical measurement, not simulation alone.",
      caption: "Compression characterization setup for helmet padding in the fitted state.",
      status: "final",
    },
    card: {
      id: "helmet-card",
      orientation: "wide",
      kind: "diagram",
      label: "06 — RESEARCH",
      subject: "Helmet cross-section schematic with pad locations and force-propagation arrows through the pad stack.",
      composition: "Wide crop, section drawn in thin line, force arrows following the load path from shell to head form.",
      lighting: "Flat vector artwork on eggshell; steel linework with blue force vectors.",
      purpose: "Read immediately as research rather than product work.",
      status: "concept",
    },
    sections: [
      {
        id: "research",
        title: "Research",
        body: [
          "Impact mechanics and force propagation in advanced combat helmet systems.",
        ],
        media: [
          {
            id: "helmet-schematic",
            orientation: "landscape",
            kind: "diagram",
            label: "06.1 — SCHEMATIC",
            subject: "Helmet and padding schematic: shell, pad positions, standoff and contact regions labelled.",
            composition: "Section view with clear labels and dimension lines; head form shown as a neutral outline.",
            lighting: "Flat technical drawing on eggshell, steel linework, restrained scientific color.",
            purpose: "Orient a reader who has never looked inside a helmet system.",
            caption: "Pad locations and contact regions.",
            status: "concept",
          },
        ],
      },
      {
        id: "method",
        title: "Method",
        body: [
          "Quantified helmet padding precompression through experimental testing, as an input to finite-element analysis.",
        ],
        media: [
          {
            id: "helmet-data",
            orientation: "landscape",
            kind: "data",
            label: "06.3 — DATA",
            subject: "Force-deflection curves for pad specimens, with the fitted precompression state marked on each curve.",
            composition: "Single chart, thin axes, several series, precompression marked by a vertical datum on each curve.",
            lighting: "Flat chart on eggshell; steel series lines, one blue datum marker.",
            purpose: "Show quantitative work and the specific quantity the research extracted.",
            caption: "Representative force-deflection behavior with the fitted state marked.",
            status: "representative",
          },
        ],
      },
      {
        id: "publication",
        title: "Publication",
        body: [
          "Contributed to research published in Annals of Biomedical Engineering, Volume 53.",
        ],
      },
    ],
    gallery: [
      {
        id: "helmet-g1",
        orientation: "detail",
        kind: "photograph",
        label: "06.4 — SPECIMEN",
        subject: "Close-up of a pad specimen under load with instrumentation in contact.",
        composition: "Tight crop on the contact region, compression visible at the pad face.",
        lighting: "Even lab light, moderate contrast, plain background.",
        purpose: "Show the measurement happening at the scale it happened.",
        status: "final",
      },
      {
        id: "helmet-g2",
        orientation: "square",
        kind: "diagram",
        label: "06.5 — MODEL",
        subject: "Simplified finite-element representation of the pad-and-shell system: coarse mesh, boundary conditions, load application point.",
        composition: "Square, mesh drawn as thin linework, constraints and load marked with standard symbols.",
        lighting: "Flat diagram on eggshell, pale mesh, blue load arrow.",
        purpose: "Connect the bench measurement to the analysis it fed.",
        caption: "Simplified representation of the modelled system. Illustrative of the analysis approach, not the published mesh.",
        status: "representative",
      },
    ],
    reflection: [],
  },
];

/* --------------------------------------------------------------
   Derived helpers
   -------------------------------------------------------------- */

/**
 * Homepage selection, in display order. The first entry gets the large
 * `feature` spread, so this order is a curatorial choice and is deliberately
 * independent of archive order.
 */
export const featuredSlugs = [
  "stryker-fixture-designs",
  "x-ray-scanner-lumafield",
  "sageware-textile-upcycling",
  "uplift-mobility-device",
] as const;

export function getProject(slug: string): Project | undefined {
  return projects.find((p) => p.slug === slug);
}

export function getFeaturedProjects(): Project[] {
  return featuredSlugs
    .map((slug) => getProject(slug))
    .filter((p): p is Project => Boolean(p));
}

/** Next project in archive order, wrapping at the end. */
export function getNextProject(slug: string): Project {
  const i = projects.findIndex((p) => p.slug === slug);
  return projects[(i + 1) % projects.length];
}
