import type { Project, ProjectCategory } from "@/lib/types";

/**
 * Every case study on the site.
 *
 * Order here sets the order everywhere: homepage spreads, archive, sitemap and
 * next/prev links. To add a project, append an object and give it the next
 * index. To add a real photograph, drop the file in /public/images and set
 * `src` + `alt` on the matching image brief.
 */

export const projectCategories: ProjectCategory[] = [
  "Technical Leadership",
  "Automation / Motion Systems",
  "Product Development",
  "R&D Testing",
  "Medical / Human-Centered Design",
  "Sustainability",
  "Research",
  "Experimental Design",
];

export const projects: Project[] = [
  /* ==============================================================
     01 — PRECISION OPTICAL POSITIONING FIXTURE
     ============================================================== */
  {
    slug: "precision-optical-positioning-fixture",
    index: "01",
    title: "Precision Optical Positioning Fixture",
    shortTitle: "Optical Fixture",
    organization: "Stryker Endoscopy",
    role: "R&D Mechanical Engineering Co-op",
    timeline: "January 2026 – June 2026",
    status: "Complete",
    theme: "dark",
    categories: [
      "R&D Testing",
      "Experimental Design",
      "Automation / Motion Systems",
      "Medical / Human-Centered Design",
    ],
    projectType: [
      "R&D Engineering",
      "Experimental Design",
      "Precision Motion",
      "Verification + Validation",
      "Medical Devices",
    ],
    cardSummary:
      "An optical positioning bench with four motorized and four manual axes, 10 µm resolution, replacing a fully manual setup.",
    summary:
      "Precisely constrains and moves optical devices with respect to a target. Four motorized and four manual axes, 10 µm resolution, inside a blackout cage. Replaced a completely manual bench.",
    tools: ["SOLIDWORKS", "Creo", "HALT chamber", "Standard + torsional Instron", "One-off fixtures", "Excel"],
    focus: [],
    specs: [
      { label: "Positioning resolution", value: "10 µm" },
      { label: "Motorized axes", value: "4" },
      { label: "Manual axes", value: "4" },
      { label: "Optical control", value: "Complete blackout cage" },
      { label: "Fixture value", value: "≈ $25,000" },
    ],
    hero: {
      id: "stryker-hero",
      orientation: "landscape",
      kind: "cad-render",
      label: "01.0 — GANTRY ASSEMBLY",
      subject: "The gantry assembly with travel annotated on each axis.",
      composition:
        "Wide, low, tightly cropped so the stage stack fills the frame; coordinate triad and axis labels in the lower left; deliberately anonymous hardware.",
      lighting:
        "Near-black ground, single hard key raking across anodized and machined surfaces, deep shadow, no fill — the visual language of an optical bench.",
      purpose:
        "Communicate precision and experimental discipline while showing nothing proprietary.",
      caption: "The gantry assembly, with each axis of travel annotated.",
      status: "final",
      src: "/images/optics-bench-gantry-cad.jpg",
      alt: "CAD assembly of the optical positioning gantry:a vertical tower on a two-axis base stage with an articulated head at the top, travel arrows marking each axis of motion.",
      width: 940,
      height: 1216,
    },
    card: {
      id: "stryker-card",
      orientation: "portrait",
      kind: "photograph",
      label: "01 — PRECISION",
      subject: "The blackout cage open, showing the bench inside.",
      composition: "Extreme close crop, strong diagonal, graduations legible, everything else falling to black.",
      lighting: "Single hard raking key on near-black ground; specular highlight along one machined edge only.",
      purpose: "Give the homepage its one dark, controlled, high-precision note.",
      status: "final",
      src: "/images/optics-bench-cage-open.jpg",
      alt: "The blackout cage with its door open, the scope fixture and target stage visible inside.",
      width: 1500,
      height: 2000,
      caption: "The bench inside its blackout cage.",
    },
    sections: [
            {
        id: "imatest",
        title: "Imatest manual adjustment",
        body: [
          "Purely motorized adjustment risks collision, so a lab jack was incorporated beneath the larger light box.",
          "The light pad kept its functionality, and the offset of the light box was designed in.",
        ],
        media: [
          {
            id: "stryker-g3",
            orientation: "portrait",
            kind: "data",
            label: "01.6 — LIGHT BOX",
            subject: "Light box and lab jack installed.",
            composition: "Square, single chart, thin rules, no gridline clutter, values unlabelled or normalized.",
            lighting: "Flat chart on near-black, pale linework, one blue series.",
            purpose: "Show familiarity with quantitative test interpretation without publishing any real data.",
            caption: "Light box on its lab jack — manual height adjustment, retained to avoid collision risk.",
            status: "final",
            src: "/images/optics-bench-lightbox-installed.jpg",
            alt: "The light box mounted on a lab jack inside the cage, positioned above the target stage.",
            width: 1440,
            height: 1920,
          },
          {
            id: "ob-im1",
            orientation: "panoramic",
            kind: "cad-render",
            label: "01.20 — LIGHT PAD MOUNT",
            subject: "CAD of the light pad mounting under the stage.",
            composition: "As drawn.",
            lighting: "Flat CAD shading.",
            purpose: "Document the design.",
            caption: "The light pad keeps its function, mounted under the stage.",
            status: "final",
            src: "/images/imatest-lightpad-mount.png",
            alt: "CAD view of a slim bracket mounted beneath an aluminium extrusion frame.",
            width: 982,
            height: 352,
          },
          {
            id: "ob-im2",
            orientation: "landscape",
            kind: "cad-render",
            label: "01.21 — STAGE UNDERSIDE",
            subject: "CAD of the stage underside with the drive hardware.",
            composition: "As drawn.",
            lighting: "Flat CAD shading.",
            purpose: "Document the design.",
            caption: "Stage underside: drive hardware and the lab jack mount.",
            status: "final",
            src: "/images/imatest-underside.png",
            alt: "CAD view from below of a frame with a motor and lead screw between the rails.",
            width: 904,
            height: 553,
          },
          {
            id: "ob-im3",
            orientation: "landscape",
            kind: "cad-render",
            label: "01.22 — JACK ARM",
            subject: "CAD of the lab jack support arm.",
            composition: "As drawn.",
            lighting: "Flat CAD shading.",
            purpose: "Document the design.",
            caption: "Support arm for the lab jack, lightened where it could be.",
            status: "final",
            src: "/images/imatest-jack-arm.png",
            alt: "CAD view of a flat machined arm with triangular cutouts and mounting holes.",
            width: 860,
            height: 589,
          },
          {
            id: "ob-im4",
            orientation: "square",
            kind: "cad-render",
            label: "01.23 — ARM PAIR",
            subject: "CAD of the paired support arms.",
            composition: "As drawn.",
            lighting: "Flat CAD shading.",
            purpose: "Document the design.",
            caption: "The arms paired up.",
            status: "final",
            src: "/images/imatest-arm-pair.png",
            alt: "CAD view of two machined arms with lightening cutouts arranged side by side.",
            width: 467,
            height: 507,
          },
          {
            id: "ob-im5",
            orientation: "panoramic",
            kind: "cad-render",
            label: "01.24 — BASE PLATE",
            subject: "CAD of the base plate the jack mounts to.",
            composition: "As drawn.",
            lighting: "Flat CAD shading.",
            purpose: "Document the design.",
            caption: "Base plate for the jack assembly.",
            status: "final",
            src: "/images/imatest-base-plate.png",
            alt: "CAD view of a long flat plate with lightening cutouts and bolt holes.",
            width: 672,
            height: 161,
          },
        ],
      },
      {
        id: "gantry-height",
        title: "Gantry height",
        body: [
          "The original height could not use the full Z-axis range of motion.",
          "The offset was increased to accommodate the Imatest light box.",
        ],
        media: [
          {
            id: "stryker-g6",
            orientation: "landscape",
            kind: "cad-render",
            label: "01.9 — GANTRY HEIGHT",
            subject: "CAD showing the increased gantry offset.",
            composition: "As shot on the bench.",
            lighting: "Available light.",
            purpose: "Document the build and the fixture family as delivered.",
            caption: "Gantry offset increased — the original height could not use the full Z travel.",
            status: "final",
            src: "/images/optics-bench-gantry-height-cad.png",
            alt: "CAD elevation of a gantry tower showing an increased mounting offset above the base.",
            width: 742,
            height: 495,
          },
          {
            id: "ob-gh2",
            orientation: "square",
            kind: "cad-render",
            label: "01.25 — OFFSET DETAIL",
            subject: "CAD detail of the increased mounting offset.",
            composition: "As drawn.",
            lighting: "Flat CAD shading.",
            purpose: "Document the design.",
            caption: "The increased offset, in detail.",
            status: "final",
            src: "/images/gantry-height-detail.png",
            alt: "CAD detail of a bracket raising a tower above its base plate.",
            width: 520,
            height: 475,
          },
        ],
      },
            {
        id: "fixtures",
        title: "Fixtures",
        body: [
          "A machined universal clamp with printed inserts fixtures any size or diameter scope.",
          "A second fixture holds any size flexible scope tip.",
        ],
        media: [
          {
            id: "stryker-g1",
            orientation: "detail",
            kind: "cad-render",
            label: "01.4 — UNIVERSAL CLAMP",
            subject: "Machined universal scope clamp.",
            composition: "Macro crop, single component centered, deep negative space around it.",
            lighting: "Single hard key on near-black, strong specular edge, no fill.",
            purpose: "Carry the precision register of the section visually.",
            status: "final",
            src: "/images/optics-bench-clamp-cad.png",
            alt: "CAD of the machined universal scope clamp, split into two halves around a central bore.",
            width: 671,
            height: 553,
            caption: "The machined universal clamp, which takes printed inserts for each scope diameter.",
          },
          {
            id: "stryker-g2",
            orientation: "detail",
            kind: "diagram",
            label: "01.5 — ALIGNMENT",
            subject: "Dimensioned clamp bore sketch.",
            composition: "Orthographic, generous margins, thin linework, labelled datums and a single beam path across frame.",
            lighting: "Pale steel linework on near-black with the beam path in blue.",
            purpose: "Show the geometric reasoning behind alignment in a way that reveals nothing specific.",
            caption: "Insert geometry: one machined clamp covers the full range of scope diameters.",
            status: "final",
            src: "/images/optics-bench-clamp-sketch.png",
            alt: "Dimensioned sketch of the clamp bore showing the 15 mm and 18 mm diameters the printed inserts span.",
            width: 716,
            height: 542,
          },
          {
            id: "stryker-g4",
            orientation: "portrait",
            kind: "photograph",
            label: "01.7 — CLAMP IN USE",
            subject: "The universal clamp holding a scope on the target stage.",
            composition: "As shot on the bench.",
            lighting: "Available light.",
            purpose: "Document the build and the fixture family as delivered.",
            caption: "The clamp in use, holding a scope on the stage.",
            status: "final",
            src: "/images/optics-bench-clamp-in-use.jpg",
            alt: "A machined clamp mounted on a precision stage gripping the shaft of an endoscope.",
            width: 1500,
            height: 2000,
          },
          {
            id: "stryker-g5",
            orientation: "landscape",
            kind: "cad-render",
            label: "01.8 — FLEXIBLE TIP FIXTURE",
            subject: "CAD of the fixture for holding a flexible scope tip.",
            composition: "As shot on the bench.",
            lighting: "Available light.",
            purpose: "Document the build and the fixture family as delivered.",
            caption: "A second fixture family holds flexible scope tips of any size.",
            status: "final",
            src: "/images/optics-bench-flex-tip-cad.png",
            alt: "CAD view of a low block fixture with a shaped channel for holding a flexible scope tip.",
            width: 680,
            height: 442,
          },
        ],
      },
      {
        id: "cage",
        title: "Blackout cage",
        body: [
          "A blackout cage encloses the bench for complete optical isolation.",
        ],
        media: [
          {
            id: "stryker-cage",
            orientation: "portrait",
            kind: "photograph",
            label: "01.2 — BLACKOUT CAGE",
            subject: "The blackout cage, door open.",
            composition: "Portrait, straight-on, enclosure filling frame, one panel open to show interior depth and light trapping.",
            lighting: "Very low key, faint edge light defining panel seams, interior reading as genuine black.",
            purpose: "Convey experimental control and optical discipline while showing nothing proprietary.",
            caption: "The blackout cage open, with the scope fixture and target stage inside.",
            status: "final",
            src: "/images/optics-bench-cage-open.jpg",
            alt: "The blackout cage with its door open, the scope fixture and target stage visible inside.",
            width: 1500,
            height: 2000,
          },
          {
            id: "stryker-g11",
            orientation: "portrait",
            kind: "photograph",
            label: "01.14 — CAGE CLOSED",
            subject: "The blackout cage closed for a run.",
            composition: "As shot on the bench.",
            lighting: "Available light.",
            purpose: "Document the build and the fixture family as delivered.",
            caption: "Closed for a run — complete optical isolation from ambient light.",
            status: "final",
            src: "/images/optics-bench-cage-closed.jpg",
            alt: "A matte black enclosure with its door closed on a laboratory bench.",
            width: 1500,
            height: 2000,
          },
        ],
      },
{
        id: "tower",
        title: "Tower mounting",
        body: [
          "Tower retention force was too low.",
          "The recession was increased to allow placement of two magnets.",
        ],
        media: [
          {
            id: "stryker-g7",
            orientation: "square",
            kind: "cad-render",
            label: "01.10 — TOWER MOUNTING",
            subject: "CAD of the recessed tower mount with two magnets.",
            composition: "As shot on the bench.",
            lighting: "Available light.",
            purpose: "Document the build and the fixture family as delivered.",
            caption: "Tower retention was too weak; the recess was deepened for a second magnet.",
            status: "final",
            src: "/images/optics-bench-tower-mount-cad.png",
            alt: "CAD detail of a recessed mounting pocket sized for two cylindrical magnets.",
            width: 500,
            height: 489,
          },
        ],
      },
      {
        id: "build",
        title: "Build",
        body: [
          "Machined, printed, assembled and wired in-house.",
        ],
        media: [
          {
            id: "stryker-g8",
            orientation: "portrait",
            kind: "photograph",
            label: "01.11 — MACHINING",
            subject: "Machining a fixture component on the mill.",
            composition: "As shot on the bench.",
            lighting: "Available light.",
            purpose: "Document the build and the fixture family as delivered.",
            caption: "Machining fixture components in-house.",
            status: "final",
            src: "/images/optics-bench-build-mill.jpg",
            alt: "An end mill cutting an aluminium extrusion held in a milling vice.",
            width: 1500,
            height: 2000,
          },
          {
            id: "stryker-g9",
            orientation: "portrait",
            kind: "photograph",
            label: "01.12 — ALIGNMENT",
            subject: "Indicating a part in before machining.",
            composition: "As shot on the bench.",
            lighting: "Available light.",
            purpose: "Document the build and the fixture family as delivered.",
            caption: "Indicating in before cutting — the alignment features had to be right.",
            status: "final",
            src: "/images/optics-bench-build-indicator.jpg",
            alt: "A dial indicator on a magnetic base checking a part clamped in a vice on a surface plate.",
            width: 1500,
            height: 2000,
          },
          {
            id: "stryker-g10",
            orientation: "portrait",
            kind: "photograph",
            label: "01.13 — WIRING",
            subject: "Wiring the controller and motion hardware.",
            composition: "As shot on the bench.",
            lighting: "Available light.",
            purpose: "Document the build and the fixture family as delivered.",
            caption: "Wiring the controller: the build included the electrical side, not just the mechanics.",
            status: "final",
            src: "/images/optics-bench-build-wiring.jpg",
            alt: "Hands soldering a connector at a bench beside an equipment enclosure with terminal blocks.",
            width: 1500,
            height: 2000,
          },
          {
            id: "ob-b4",
            orientation: "detail",
            kind: "photograph",
            label: "01.26 — CUTTING EXTRUSION",
            subject: "Cutting aluminium extrusion to length on the chop saw.",
            composition: "As drawn.",
            lighting: "Flat CAD shading.",
            purpose: "Document the design.",
            caption: "Cutting extrusion to length.",
            status: "final",
            src: "/images/optics-bench-build-chopsaw.jpg",
            alt: "A person cutting an aluminium extrusion on a mitre saw at a workshop bench.",
            width: 2000,
            height: 1500,
          },
        ],
      },
    ],
    gallery: [],
    reflection: [],
    confidentiality: "Proprietary information withheld.",
  },
  {
    slug: "stryker-fixture-designs",
    index: "02",
    title: "Stryker Fixture Designs",
    shortTitle: "Fixture Designs",
    organization: "Stryker Endoscopy",
    role: "R&D Mechanical Engineering Co-op",
    timeline: "January 2026 – June 2026",
    status: "Complete",
    theme: "light",
    categories: [
      "R&D Testing",
      "Experimental Design",
      "Medical / Human-Centered Design",
    ],
    projectType: [
      "R&D Engineering",
      "Design for Test",
      "Mechanical Reliability",
      "Verification + Validation",
      "Medical Devices",
    ],
    cardSummary:
      "Fixtures for laser intensity, interface reliability, focus ring torque and vibration testing.",
    summary:
      "Test fixtures for a camera head, coupler and camera control unit: laser intensity, interface reliability, focus ring torque, and front cover vibration testing.",
    tools: [
      "SOLIDWORKS",
      "Creo",
      "MJF + MJP printing",
      "Instron",
      "Torsional Instron",
      "Vibration table",
      "Manual mill + lathe",
    ],
    focus: [],
    specs: [
      { label: "Print processes", value: "MJF, MJP for alignment-critical features" },
      { label: "Test types", value: "Optical, torque, vibration, lifecycle" },
      { label: "Subsystems", value: "Camera head, coupler, camera control unit" },
    ],
    hero: {
      id: "fixtures-hero",
      orientation: "detail",
      kind: "cad-render",
      label: "02.0 — LASER INTENSITY FIXTURE",
      subject: "The laser intensity fixture, full configuration.",
      composition: "Three-quarter view with the full fixture and its rail in frame.",
      lighting: "Even bench lighting.",
      purpose: "Show the delivered hardware rather than the CAD intent.",
      caption:
        "The laser intensity fixture as built, after five revisions.",
      status: "final",
      src: "/images/thermopile-fixture-cad.png",
      alt: "CAD assembly of the laser intensity fixture in its full configuration, with the source, a scope body and the sensor in line along a rail.",
      width: 875,
      height: 712,
    },
    card: {
      id: "fixtures-card",
      orientation: "detail",
      kind: "cad-render",
      label: "02 — DESIGN FOR TEST",
      subject: "The laser intensity fixture as built.",
      composition: "Isometric, full assembly in frame.",
      lighting: "Flat CAD shading on a pale ground.",
      purpose: "Read as precision test equipment at card size.",
      caption: "Laser intensity fixture, full configuration.",
      status: "final",
      src: "/images/thermopile-fixture-cad.png",
      alt: "CAD assembly of the laser intensity fixture in its full configuration, with the source, a scope body and the sensor in line along a rail.",
      width: 875,
      height: 712,
    },
    sections: [
      {
        id: "laser-intensity",
        title: "Laser intensity fixture",
        body: [
          "A laser intensity testing setup, with and without a scope in the path, at variable distance.",
        ],
        list: [
          "Rev 1 — basic centering, discrete distance markings.",
          "Rev 2 — changed clearances, stronger base.",
          "Rev 3 — added insert system and y-axis lock.",
          "Rev 4 — switched critical alignment features to MJP.",
          "Final — complete locking system, constrained through the coupler instead of the scope, coupler-only version added.",
        ],
        media: [
          {
            id: "fixtures-laser-cad",
            orientation: "square",
            kind: "cad-render",
            label: "02.1 — FINAL REVISION",
            subject: "CAD of the final laser intensity fixture with the locking system.",
            composition: "Isometric on a pale ground.",
            lighting: "Flat CAD shading.",
            purpose: "Show the locking and insert system that ended the revision cycle.",
            caption: "Final revision: complete locking system, constrained through the coupler.",
            status: "final",
            src: "/images/thermopile-fixture-final-cad.png",
            alt: "CAD view of a test fixture with a clamped bore, locking screws and a sliding carriage.",
            width: 554,
            height: 536,
          },
          {
            id: "fixtures-laser-built",
            orientation: "portrait",
            kind: "photograph",
            label: "02.2 — AS BUILT",
            subject: "The assembled fixture in use on the bench.",
            composition: "Close three-quarter view.",
            lighting: "Bench lighting.",
            purpose: "Show the printed inserts and locking hardware in place.",
            caption: "The fixture in use, with printed inserts seated.",
            status: "final",
            src: "/images/thermopile-fixture-built-2.jpg",
            alt: "A printed and machined fixture clamped on a bench rail holding an optical component.",
            width: 1500,
            height: 2000,
          },
          {
            id: "fx-g4",
            orientation: "landscape",
            kind: "cad-render",
            label: "02.13 — LASER FIXTURE ASSEMBLY",
            subject: "CAD of the laser intensity fixture with the sensor in place.",
            composition: "As drawn.",
            lighting: "Flat CAD shading.",
            purpose: "Document the fixture family.",
            caption: "Laser intensity fixture with the sensor mounted.",
            status: "final",
            src: "/images/thermopile-assembly-cad.png",
            alt: "CAD assembly of a test fixture with a sensor head mounted in line with a clamped optical component.",
            width: 921,
            height: 641,
          },
          {
            id: "fx-g5",
            orientation: "landscape",
            kind: "cad-render",
            label: "02.14 — DISTANCE MARKINGS",
            subject: "CAD detail of the discrete distance markings along the rail.",
            composition: "As drawn.",
            lighting: "Flat CAD shading.",
            purpose: "Document the fixture family.",
            caption: "Discrete distance markings along the rail.",
            status: "final",
            src: "/images/thermopile-distance-cad.png",
            alt: "CAD detail of a cylindrical rail with numbered graduation marks along its length.",
            width: 745,
            height: 292,
          },
          {
            id: "fx-full1",
            orientation: "panoramic",
            kind: "cad-render",
            label: "02.19 — FULL VERSION",
            subject: "CAD of the full version with a scope in the optical path.",
            composition: "As drawn.",
            lighting: "Flat CAD shading.",
            purpose: "Document the design.",
            caption: "The full version, with a scope in the optical path.",
            status: "final",
            src: "/images/laser-full-side.png",
            alt: "CAD side view of a long test fixture with a tapered scope body between the source and the sensor.",
            width: 1113,
            height: 444,
          },
          {
            id: "fx-full2",
            orientation: "landscape",
            kind: "cad-render",
            label: "02.20 — FULL VERSION DETAIL",
            subject: "CAD detail of the scope interface on the full version.",
            composition: "As drawn.",
            lighting: "Flat CAD shading.",
            purpose: "Document the design.",
            caption: "Scope interface on the full version.",
            status: "final",
            src: "/images/laser-full-detail.png",
            alt: "CAD detail of a clamped interface between a fixture body and a scope.",
            width: 552,
            height: 366,
          },
        ],
      },
            {
        id: "focus-ring",
        title: "Focus ring fixture",
        body: [
          "A focus ring geometry change meant actuation torque had to be tested across the lifecycle, across different fin styles.",
          "I used this fixture to perform torsional Instron testing and torque gauge testing.",
        ],
        media: [
          {
            id: "fixtures-focus-cad",
            orientation: "square",
            kind: "cad-render",
            label: "02.5 — FIN VARIANTS",
            subject: "CAD of the focus ring fixture with an interchangeable insert.",
            composition: "Isometric on a pale ground.",
            lighting: "Flat CAD shading.",
            purpose: "Show the interchangeable insert approach.",
            caption: "Interchangeable inserts let one setup cover every fin style.",
            status: "final",
            src: "/images/focus-ring-fixture-cad.png",
            alt: "CAD view of a circular fixture with a toothed insert for gripping a focus ring.",
            width: 511,
            height: 520,
          },
          {
            id: "fixtures-focus-built",
            orientation: "portrait",
            kind: "photograph",
            label: "02.6 — TORSIONAL TEST",
            subject: "The focus ring fixture mounted for torque measurement.",
            composition: "Vertical, fixture and drive in frame.",
            lighting: "Bench lighting.",
            purpose: "Show the torque measurement setup.",
            caption: "Mounted for torque measurement across lifecycle.",
            status: "final",
            src: "/images/focus-ring-fixture-built.jpg",
            alt: "A fixture mounted in a torsional test frame gripping a ring-shaped component.",
            width: 1500,
            height: 2000,
          },
          {
            id: "fx-g1",
            orientation: "landscape",
            kind: "cad-render",
            label: "02.10 — PENDULUM FOCUS RING FIXTURE",
            subject: "CAD of the focus ring fixture on the pendulum body.",
            composition: "As drawn.",
            lighting: "Flat CAD shading.",
            purpose: "Document the fixture family.",
            caption: "The pendulum focus ring fixture.",
            status: "final",
            src: "/images/focus-ring-pendulum-cad.png",
            alt: "CAD view of a fixture wrapped around a cylindrical camera head body, gripping the focus ring collar.",
            width: 741,
            height: 384,
          },
          {
            id: "fx-g2",
            orientation: "square",
            kind: "cad-render",
            label: "02.11 — FIN GEOMETRY",
            subject: "CAD of a focus ring collar with its fin profile.",
            composition: "As drawn.",
            lighting: "Flat CAD shading.",
            purpose: "Document the fixture family.",
            caption: "One of the fin styles the torque test had to cover.",
            status: "final",
            src: "/images/focus-ring-collar-cad.png",
            alt: "CAD view of a ring collar with raised fins on its outer face.",
            width: 504,
            height: 523,
          },
          {
            id: "fx-g3",
            orientation: "landscape",
            kind: "diagram",
            label: "02.12 — FIN SKETCH",
            subject: "Dimensioned sketch of the fin profile.",
            composition: "As drawn.",
            lighting: "Flat CAD shading.",
            purpose: "Document the fixture family.",
            caption: "Fin profile, dimensioned.",
            status: "final",
            src: "/images/focus-ring-sketch.png",
            alt: "A dimensioned CAD sketch of a curved fin profile with radii and angles called out.",
            width: 844,
            height: 382,
          },
        ],
      },
{
        id: "interface-reliability",
        title: "Interface mechanical reliability",
        body: [
          "Simulates scope use with a coupler, and fully constrains the next-generation coupler to the test fixture.",
        ],
        media: [
          {
            id: "fixtures-endoclamp-cad",
            orientation: "portrait",
            kind: "photograph",
            label: "02.3 — RETENTION FIXTURE",
            subject: "The retention fixture on the bench with a coupler constrained.",
            composition: "Isometric, full assembly.",
            lighting: "Flat CAD shading.",
            purpose: "Show how the coupler is fully constrained to the rig.",
            caption: "Retention fixture — the coupler is fully constrained to the test rig.",
            status: "final",
            src: "/images/endoclamp-fixture-cad.jpg",
            alt: "A test rig built from extrusion, with a coupler clamped upright beneath a linear actuator on a bench.",
            width: 579,
            height: 738,
          },
          {
            id: "fixtures-endoclamp-built",
            orientation: "portrait",
            kind: "photograph",
            label: "02.4 — ON TEST",
            subject: "The retention fixture set up for a reliability run.",
            composition: "Vertical, fixture and load frame in view.",
            lighting: "Bench lighting.",
            purpose: "Show the fixture in the test configuration.",
            caption: "Set up for a mechanical reliability run.",
            status: "final",
            src: "/images/endoclamp-fixture-built.jpg",
            alt: "A test fixture mounted in a load frame with a coupler clamped in position.",
            width: 1500,
            height: 2000,
          },
          {
            id: "fx-g6",
            orientation: "portrait",
            kind: "cad-render",
            label: "02.15 — CLAMP BODY",
            subject: "CAD of the clamp body that constrains the coupler.",
            composition: "As drawn.",
            lighting: "Flat CAD shading.",
            purpose: "Document the fixture family.",
            caption: "The clamp body, labelled for orientation.",
            status: "final",
            src: "/images/endoclamp-clamp-cad.png",
            alt: "CAD view of a cylindrical clamp body with a tapered collar and a cross-drilled base.",
            width: 396,
            height: 637,
          },
          {
            id: "fx-g7",
            orientation: "portrait",
            kind: "photograph",
            label: "02.16 — PRINTED PARTS",
            subject: "The printed clamp components before assembly.",
            composition: "As drawn.",
            lighting: "Flat CAD shading.",
            purpose: "Document the fixture family.",
            caption: "Printed clamp components, as they came off the machine.",
            status: "final",
            src: "/images/endoclamp-printed-parts.jpg",
            alt: "Two teal 3D-printed conical fixture bodies on a bench before assembly.",
            width: 1500,
            height: 2000,
          },
        ],
      },
      {
        id: "ccu",
        title: "Camera control unit — front cover and vibration",
        body: [
          "Front cover mounting and cable receptacle changes needed cable receptacle backout resilience verified under vibration.",
        ],
        media: [
          {
            id: "fixtures-ccu-cad",
            orientation: "wide",
            kind: "cad-render",
            label: "02.7 — FRONT COVER",
            subject: "CAD of the revised front cover mounting and cable receptacle.",
            composition: "Front elevation.",
            lighting: "Flat CAD shading.",
            purpose: "Show the mounting change that required verification.",
            caption: "Revised front cover mounting and cable receptacle.",
            status: "final",
            src: "/images/ccu-front-cover-cad.png",
            alt: "CAD front elevation of a rack-style enclosure cover with connector openings.",
            width: 1337,
            height: 721,
            wide: true,
          },
          {
            id: "fixtures-ccu-vibe",
            orientation: "detail",
            kind: "photograph",
            label: "02.8 — VIBRATION SETUP",
            subject: "The unit mounted for vibration testing.",
            composition: "Three-quarter view of the table and mounted unit.",
            lighting: "Lab lighting.",
            purpose: "Show the vibration test configuration.",
            caption: "Mounted for vibration testing.",
            status: "final",
            src: "/images/ccu-vibration-setup.jpg",
            alt: "An electronics enclosure strapped to a vibration table with instrumentation cables attached.",
            width: 2000,
            height: 1500,
          },
          {
            id: "fx-g9",
            orientation: "landscape",
            kind: "diagram",
            label: "02.18 — RECEPTACLE DETAIL",
            subject: "Dimensioned drawing of the cable receptacle cutout.",
            composition: "As drawn.",
            lighting: "Flat CAD shading.",
            purpose: "Document the fixture family.",
            caption: "Cable receptacle cutout, dimensioned.",
            status: "final",
            src: "/images/ccu-front-cover-drawing.png",
            alt: "An engineering drawing of a rectangular plate with a bolt circle and chamfer callouts.",
            width: 709,
            height: 423,
            wide: true,
          },
        ],
      },
          ],
    gallery: [],
    reflection: [],
    confidentiality: "Proprietary information withheld.",
  },
  {
    slug: "sageware-textile-upcycling",
    index: "03",
    title: "Sageware Textile Upcycling System",
    shortTitle: "Sageware",
    organization: "Generate Product Development Studio",
    role: "Mechanical Engineer",
    timeline: "September 2025 – December 2025",
    status: "Fully assembled",
    theme: "light",
    accent: "#6B7F4E",
    categories: [
      "Product Development",
      "Sustainability",
      "Automation / Motion Systems",
    ],
    projectType: [
      "Product Development",
      "Sustainability",
      "Automation / Motion Systems",
      "Tooling",
      "Additive Manufacturing",
    ],
    cardSummary:
      "Upcycling fabric scraps into beads that can be used in jewelry designs or sold wholesale.",
    summary:
      "Upcycling fabric scraps into beads that can be used in jewelry designs or sold wholesale.",
    tools: ["Onshape", "SLA resin", "FDM + heat-set inserts", "Tool steel (Xometry)", "Lead screw + linear rail", "8020 frame"],
    team: "Generate product-development team",
    focus: ["Clean, consistent cuts", "Repeatability", "Tolerance stackup", "Machining cost"],
    specs: [
      { label: "Process", value: "Heating, molding, cutting, and dispensing" },
      { label: "Input", value: "Two fabric layers with a PC-ABS hot glue sheet sandwiched between them" },
      { label: "Heating", value: "Heated plate maintained at approximately 90°C" },
      { label: "Bead", value: "Five-pointed flower, cut around a molded dome" },
      { label: "Cutting stamp", value: "Custom-machined hard tool steel, five flower-shaped blades" },
      { label: "Jig and cutting board", value: "SLA resin" },
      { label: "Stamp actuation", value: "Lead screw at one end, linear rail on the other" },
    ],
    hero: {
      id: "sageware-hero",
      orientation: "wide",
      kind: "cad-render",
      label: "03.0 — SYSTEM",
      subject: "Render of the complete machine in its enclosure.",
      composition: "As rendered.",
      lighting: "Studio render.",
      purpose: "Show the product.",
      caption: "External View of Sageware",
      status: "final",
      src: "/images/sageware-external-view.jpg",
      alt: "Render of the Sageware machine: a rounded pink enclosure with a pull-out fabric insertion tray, a small LCD screen, hinged collection doors at the front and removable side panels.",
      width: 2048,
      height: 1154,
    },
    card: {
      id: "sageware-card",
      orientation: "detail",
      kind: "cad-render",
      label: "03 — CUTTING SUBSYSTEM",
      subject: "CAD of the cutting subsystem.",
      composition: "As drawn.",
      lighting: "Flat CAD shading.",
      purpose: "The heart of the cutting subsystem is a custom-machined steel stamp with five flower-shaped blades.",
      caption: "Cutting Subsystem Whole View",
      status: "final",
      src: "/images/sageware-cutting-subsystem.png",
      alt: "CAD of the cutting subsystem: a lead screw and gear drive at one end, a linear rail at the other, and a stamp jig carrying five flower-shaped blades above a cutting plate.",
      width: 923,
      height: 754,
    },
    sections: [
      {
        id: "system",
        title: "System",
        body: [
          "Sageware’s process consists of four steps: heating, molding, cutting, and dispensing.",
        ],
        media: [
          {
            id: "sageware-machine",
            orientation: "square",
            kind: "photograph",
            label: "03.1 — ASSEMBLED",
            subject: "The assembled machine.",
            composition: "As shot.",
            lighting: "Available light.",
            purpose: "Document the build.",
            caption: "The assembled machine.",
            status: "final",
            src: "/images/sageware-machine.jpg",
            alt: "The assembled Sageware machine on a workshop bench: a pink and white enclosure with an LCD screen, a fabric insertion tray and collection doors.",
            width: 1974,
            height: 2000,
          },
          {
            id: "sageware-architecture",
            orientation: "wide",
            kind: "cad-render",
            label: "03.2 — INTERNAL ARCHITECTURE",
            subject: "Render of the machine without its enclosure.",
            composition: "As rendered.",
            lighting: "Studio render.",
            purpose: "Document the design.",
            caption: "Internal Architecture",
            status: "final",
            src: "/images/sageware-internal-architecture.jpg",
            alt: "Render of the machine without its enclosure: stepper motors, the slanted insertion plate, the cutting stamp's gears and lead screw, belt-driven rollers, and two angled ramps below.",
            width: 1570,
            height: 782,
            wide: true,
          },
        ],
      },
      {
        id: "cutting",
        title: "Cutting",
        body: [
          "The heart of the cutting subsystem is a custom-machined steel stamp with five flower-shaped blades. For this, hard tool steel was used to ensure retention of a sharp edge with repeated use, requiring minimal service (and keeping cuts cleaner, as the client wanted).",
          "This is fastened to an SLA resin jig for interfacing with power transfer components, reducing the total stock used (and therefore machining cost) when compared with machining the jig together with the stamp as one part. The jig/insert assembly is actuated vertically by a lead screw at one end, and fastened by a linear rail on the other.",
        ],
        media: [
          {
            id: "sageware-stamp-drawing",
            orientation: "landscape",
            kind: "photograph",
            label: "03.3 — STAMP AND DRAWING",
            subject: "The machined steel stamp on its drawing.",
            composition: "As shot.",
            lighting: "Available light.",
            purpose: "Document the build.",
            caption: "The machined steel stamp on its drawing.",
            status: "final",
            src: "/images/sageware-stamp-drawing.jpg",
            alt: "A steel bar with five flower-shaped cutting blades lying on its dimensioned engineering drawing.",
            width: 2000,
            height: 1500,
          },
          {
            id: "sageware-stamp",
            orientation: "portrait",
            kind: "photograph",
            label: "03.4 — STAMP",
            subject: "The machined steel stamp.",
            composition: "As shot.",
            lighting: "Available light.",
            purpose: "Document the build.",
            caption: "Five flower-shaped blades.",
            status: "final",
            src: "/images/sageware-stamp.jpg",
            alt: "The machined steel stamp on a white bench: a bar with five flower-shaped blades along its length.",
            width: 1500,
            height: 2000,
          },
          {
            id: "sageware-cutting",
            orientation: "detail",
            kind: "cad-render",
            label: "03.5 — CUTTING SUBSYSTEM",
            subject: "CAD of the cutting subsystem.",
            composition: "As drawn.",
            lighting: "Flat CAD shading.",
            purpose: "Document the design.",
            caption: "Cutting Subsystem Whole View",
            status: "final",
            src: "/images/sageware-cutting-subsystem.png",
            alt: "CAD of the cutting subsystem: a lead screw and gear drive at one end, a linear rail at the other, and a stamp jig carrying five flower-shaped blades above a cutting plate.",
            width: 923,
            height: 754,
          },
          {
            id: "sageware-cutting-built",
            orientation: "landscape",
            kind: "photograph",
            label: "03.6 — AS BUILT",
            subject: "The cutting subsystem assembled in the frame.",
            composition: "As shot.",
            lighting: "Available light.",
            purpose: "Document the build.",
            caption: "The cutting subsystem in the frame.",
            status: "final",
            src: "/images/sageware-cutting-built.jpg",
            alt: "The cutting subsystem assembled in its aluminium extrusion frame, with the stamp carried on a lead screw at one end, above the machine's electronics.",
            width: 2000,
            height: 1500,
          },
        ],
      },
    ],
    gallery: [],
    reflection: [],
  },
  {
    slug: "uplift-mobility-device",
    index: "04",
    title: "Uplift Mobility Device",
    shortTitle: "Uplift",
    organization: "Generate Product Development Studio",
    role: "Mechanical Engineer",
    timeline: "December 2024 – April 2025",
    status: "Prototype complete",
    theme: "light",
    accent: "#3E5C76",
    categories: [
      "Medical / Human-Centered Design",
      "Product Development",
    ],
    projectType: [
      "Human-Centered Design",
      "Product Development",
      "Mechanisms",
      "Prototyping",
      "Electromechanical Integration",
    ],
    cardSummary:
      "An assistive mobility device that not only functions as a walker and rollator but also provides powered assistance to help users safely and comfortably sit down and stand up.",
    summary:
      "An assistive mobility device that not only functions as a walker and rollator but also provides powered assistance to help users safely and comfortably sit down and stand up.",
    tools: ["Onshape", "FDM (PLA)", "SLA (Grey Pro)", "Shop tools"],
    team: "Mechanical and electrical sub-teams at Generate",
    focus: ["Mechanisms", "Human factors", "Integration", "Weight", "Fast iteration"],
    specs: [
      { label: "Device", value: "Walker and rollator with powered assistance to sit down and stand up" },
      { label: "Users", value: "Elderly individuals with difficulty transitioning between sitting and standing" },
      { label: "Weight", value: "≈ 50 lb target, met" },
      { label: "Actuation", value: "Four stepper motors, 12 in × 20 mm hardened steel ball screws" },
      { label: "Frame", value: "1-1/2 in aluminum conduit, FDM PLA connectors" },
      { label: "My scope", value: "Framing connections, battery box, mech/elec integration" },
      { label: "Prototyping", value: "FDM PLA and SLA Grey Pro, iterated in Onshape" },
    ],
    hero: {
      id: "uplift-hero",
      orientation: "square",
      kind: "photograph",
      label: "04.0 — DEVICE",
      subject: "The finished walker prototype, seat and powered legs visible.",
      composition: "As shot.",
      lighting: "Available light.",
      purpose: "Show the finished device.",
      caption: "The finished prototype, with powered legs, integrated seat and cable carriers on each side.",
      status: "prototype",
      src: "/images/uplift-showcase.jpg",
      alt: "The white walker prototype on display: aluminium tube frame, printed joints, a black seat, a backrest housing, handles with controls, and cable carriers running down each side to the powered legs.",
      width: 1500,
      height: 1480,
    },
    card: {
      id: "uplift-card",
      orientation: "portrait",
      kind: "cad-render",
      label: "04 — MOBILITY",
      subject: "Full CAD assembly of the walker.",
      composition: "As drawn.",
      lighting: "Flat CAD shading.",
      purpose: "Full CAD assembly: frame, seat, backrest housing, handles and four powered legs.",
      caption: "Full assembly.",
      status: "final",
      src: "/images/uplift-assembly-cad.png",
      alt: "CAD assembly of the walker: tube frame, seat, backrest housing and handles above four powered legs on caster wheels.",
      width: 652,
      height: 737,
    },
    sections: [
      {
        id: "overview",
        title: "System overview",
        body: [],
        media: [
          {
            id: "uplift-system-overview",
            orientation: "landscape",
            kind: "photograph",
            label: "04.1 — SYSTEM OVERVIEW",
            subject: "The prototype from the back and the front, with its main components labelled.",
            composition: "As shot.",
            lighting: "Available light.",
            purpose: "Document the build.",
            caption: "System Overview",
            status: "final",
            src: "/images/uplift-system-overview.jpg",
            alt: "Two photos of the Uplift walker prototype, from the back and the front, labelled: backrest, truss supports, lead screw covers, motor housing, cable carriers, UI, custom hand brakes and sliding mechanism.",
            width: 960,
            height: 720,
            wide: true,
          },
          {
            id: "uplift-assembly",
            orientation: "portrait",
            kind: "cad-render",
            label: "04.2 — ASSEMBLY",
            subject: "Full CAD assembly of the walker.",
            composition: "As drawn.",
            lighting: "Flat CAD shading.",
            purpose: "Document the design.",
            caption: "Full assembly: frame, seat, backrest housing, handles and four powered legs.",
            status: "final",
            src: "/images/uplift-assembly-cad.png",
            alt: "CAD assembly of the walker: tube frame, seat, backrest housing and handles above four powered legs on caster wheels.",
            width: 652,
            height: 737,
          },
        ],
      },
      {
        id: "framing",
        title: "Framing connections",
        body: [
          "I led iterative development of the conduit linkages in Onshape, printed in FDM PLA and SLA Grey Pro.",
          "All parts shown in framing were FDM 3D printed out of PLA with 20% infill using Grid or Gyroid pattern.",
        ],
        media: [
          {
            id: "uplift-sliding-connector",
            orientation: "landscape",
            kind: "cad-render",
            label: "04.3 — SLIDING CONDUIT CONNECTOR",
            subject: "CAD of the 90-degree sliding conduit connector.",
            composition: "As drawn.",
            lighting: "Flat CAD shading.",
            purpose: "Document the design.",
            caption: "90-Degree Sliding Conduit Connector. The goal of this piece was to keep the front and back of the walker horizontally constrained while still allowing for relative vertical motion.",
            status: "final",
            src: "/images/uplift-sliding-conduit-connector.png",
            alt: "CAD of a grey 90-degree connector: a vertical sleeve around one conduit, with a horizontal insert pressed into a second conduit, above a motor housing.",
            width: 861,
            height: 606,
          },
          {
            id: "uplift-static-connector",
            orientation: "landscape",
            kind: "cad-render",
            label: "04.4 — STATIC CONDUIT CONNECTOR",
            subject: "CAD of the 90-degree static conduit connector.",
            composition: "As drawn.",
            lighting: "Flat CAD shading.",
            purpose: "Document the design.",
            caption: "90-Degree Static Conduit Connector. There was also a non-sliding version of this piece with two horizontal connections on the other end of the walker.",
            status: "final",
            src: "/images/uplift-static-conduit-connector.png",
            alt: "CAD of a grey static connector with two horizontal arms, joining a vertical conduit to two horizontal conduits.",
            width: 442,
            height: 376,
          },
          {
            id: "uplift-ball-nut-connector",
            orientation: "landscape",
            kind: "cad-render",
            label: "04.5 — CONDUIT-BALL NUT CONNECTOR",
            subject: "CAD of the conduit-ball nut connector.",
            composition: "As drawn.",
            lighting: "Flat CAD shading.",
            purpose: "Document the design.",
            caption: "Conduit-Ball Nut Connector. With relative motion constrained as necessary, the top of the frame needed to be mated to the legs/lead screws; this piece is screwed to the ball nuts via heat-set insert and press fit around the top of the frame's conduit.",
            status: "final",
            src: "/images/uplift-conduit-ball-nut-connector.png",
            alt: "CAD of a grey cylindrical connector around the top of a conduit, its flanged base fastened to a ball nut.",
            width: 814,
            height: 670,
          },
        ],
      },
      {
        id: "battery",
        title: "Battery box",
        body: [
          "I coordinated with the electrical sub-team to integrate the motors, house the electronics and protect the battery.",
          "A housing was designed that snugly fits the battery underneath the seat while still allowing cables to run out and power the necessary electronics.",
        ],
        media: [
          {
            id: "uplift-battery-box",
            orientation: "landscape",
            kind: "cad-render",
            label: "04.6 — BATTERY BOX",
            subject: "CAD of the battery box under the seat.",
            composition: "As drawn.",
            lighting: "Flat CAD shading.",
            purpose: "Document the design.",
            caption: "Battery Box",
            status: "final",
            src: "/images/uplift-battery-box-cad.png",
            alt: "CAD of a translucent blue battery box with four corner mounting ears and a cable cutout, mounted under the seat plate.",
            width: 882,
            height: 584,
          },
          {
            id: "uplift-battery-printed",
            orientation: "portrait",
            kind: "photograph",
            label: "04.7 — OFF THE PRINTER",
            subject: "The printed battery housing with supports attached.",
            composition: "As shot.",
            lighting: "Available light.",
            purpose: "Document the build.",
            caption: "The battery housing off the printer, tree supports still attached.",
            status: "final",
            src: "/images/uplift-battery-housing-printed.jpg",
            alt: "A hand holding a white printed housing upside down, its underside covered in branching tree supports.",
            width: 1500,
            height: 2000,
          },
          {
            id: "uplift-battery-built",
            orientation: "portrait",
            kind: "photograph",
            label: "04.8 — BATTERY FITTED",
            subject: "The printed battery housing with the battery seated.",
            composition: "As shot.",
            lighting: "Available light.",
            purpose: "Document the build.",
            caption: "The battery seated in its printed housing.",
            status: "final",
            src: "/images/uplift-battery-housing-built.jpg",
            alt: "A blue battery pack seated in a white printed housing with corner mounting ears, its leads exiting through the end cutout.",
            width: 1500,
            height: 2000,
          },
        ],
      },
    ],
    gallery: [],
    reflection: [],
  },
  {
    slug: "helmet-impact-mechanics",
    index: "05",
    title: "Helmet Impact Mechanics Research",
    shortTitle: "Helmet Impact Research",
    organization:
      "Northeastern University Center for STEM Education / Young Scholars’ Program",
    role: "Research Assistant & Co-author",
    timeline: "June 2023 – August 2023",
    status: "Published",
    theme: "light",
    accent: "#4A5D6B",
    categories: ["Research", "Experimental Design", "Medical / Human-Centered Design"],
    projectType: [
      "Research",
      "Experimental Mechanics",
      "Biomedical Engineering",
      "Finite Element Analysis",
    ],
    cardSummary:
      "To evaluate the population variation in head-to-helmet contact forces in helmet users.",
    summary:
      "To evaluate the population variation in head-to-helmet contact forces in helmet users.",
    tools: ["Force sensitive resistors", "Arduino Mega", "Digital force gauge", "Caliper stand", "Custom chinstrap tension gauges"],
    team: "University research group, Young Scholars’ Program",
    focus: ["Methodology", "Validation", "Investigation"],
    specs: [
      { label: "Publication", value: "Annals of Biomedical Engineering 53, 946–955 (2025)", href: "https://link.springer.com/article/10.1007/s10439-025-03677-3" },
      { label: "Article", value: "Measurement and Assessment of Head-to-Helmet Contact Forces" },
      { label: "Helmets", value: "Four sizes of Kevlar composite helmet, seven interior pads each" },
      { label: "Sensors", value: "A force sensitive resistor on each pad; custom chinstrap tension gauges" },
      { label: "Volunteers", value: "89 (25 female, 64 male)" },
      { label: "My contribution", value: "Methodology, validation, investigation" },
    ],
    hero: {
      id: "helmet-hero",
      orientation: "panoramic",
      kind: "diagram",
      label: "05.0 — MEASUREMENT SYSTEM",
      subject: "Measurement system diagram.",
      composition: "As published.",
      lighting: "As published.",
      purpose: "Show the instrumented helmet.",
      caption:
        "Measurement system diagram. A: Helmet with force sensitive resistor notation marked in red, other key features marked in blue. B: Detail of the chinstrap tension gauges. C: Detail of the helmet chinstrap system, aligned to correspond to the helmet shown in A",
      src: "/images/helmet-measurement-system.jpg",
      alt: "Measurement system diagram: a helmet interior with its seven instrumented pads labelled, a detail of the chinstrap tension gauges, and the chinstrap system laid flat.",
      width: 1505,
      height: 621,
    },
    card: {
      id: "helmet-card",
      orientation: "wide",
      kind: "photograph",
      label: "05 — INSTRUMENTED PADS",
      subject: "Helmet pads instrumented with contact pressure sensors.",
      composition: "As published.",
      lighting: "As published.",
      purpose: "Oregon Aero foam liner pads instrumented with contact pressure sensors.",
      caption: "Oregon Aero foam liner pads instrumented with contact pressure sensors.",
      src: "/images/helmet-instrumented-pads.jpg",
      alt: "Three foam helmet pads — circular, trapezoidal and oval — each with a square force sensitive resistor sewn on with electrical tape.",
      width: 1704,
      height: 748,
    },
    sections: [
      {
        id: "measurement",
        title: "Measurement system",
        body: [
          "A force sensitive resistor (FSR) (Adafruit Industries, LLC. New York, NY) was installed on each pad. To mount each FSR, a flexible rim was created around the perimeter of the sensor using electrical tape. The rim was sewn onto the cloth exterior of the padding, which allowed the sensors to flex and conform to the shape of the pad. Measurements were recorded using an Arduino Mega microcontroller.",
          "To measure the tension in the chinstrap, a custom mechanical force gauge was developed which replaced the original adjustment buckles in the chinstrap.",
        ],
        media: [
          {
            id: "helmet-pads",
            orientation: "wide",
            kind: "photograph",
            label: "05.1 — INSTRUMENTED PADS",
            subject: "Helmet pads instrumented with contact pressure sensors.",
            composition: "As published.",
            lighting: "As published.",
            purpose: "Document the measurement system.",
            caption:
              "Oregon Aero foam liner pads instrumented with contact pressure sensors. Left to right: Circular top pad, Trapezoidal front/back pad, oval side pad",
            src: "/images/helmet-instrumented-pads.jpg",
            alt: "Three foam helmet pads — circular, trapezoidal and oval — each with a square force sensitive resistor sewn on with electrical tape.",
            width: 1704,
            height: 748,
            wide: true,
          },
        ],
      },
      {
        id: "calibration",
        title: "Calibration",
        body: [
          "Because flexure in the FSR was observed to change the measured force value, the pressure measurement on the surface of the pad was calibrated with the FSR and pad installed in the helmet.",
          "A digital force gauge (Imada, Inc., Northbrook, IL) was used to measure the force applied to the FSR. A curved force applicator was fitted to the force gauge to emulate the curvature of the head. The force gauge was mounted on a caliper stand (Mitutoyo America Corp., Holyoke, MA) which was used to apply variable compression to the padding. A cubic spline was found to have the lowest RMS error when fitting the data so was used to relate the FSR analog value to sensor force.",
        ],
        media: [
          {
            id: "helmet-applicator",
            orientation: "wide",
            kind: "cad-render",
            label: "05.2 — FORCE APPLICATOR",
            subject: "CAD of the curved force applicator.",
            composition: "As published.",
            lighting: "As published.",
            purpose: "Document the calibration setup.",
            caption: "Force applicator used to emulate contact with the curved surface of the head",
            src: "/images/helmet-force-applicator.png",
            alt: "CAD of a disc-shaped force applicator with a curved underside and a keyhole slot, in isometric and side views.",
            width: 1280,
            height: 720,
          },
          {
            id: "helmet-calibration-curve",
            orientation: "square",
            kind: "data",
            label: "05.3 — CALIBRATION CURVE",
            subject: "Calibration curve for the helmet FSRs.",
            composition: "As published.",
            lighting: "As published.",
            purpose: "Document the calibration.",
            caption: "Calibration curve for helmet FSRs",
            src: "/images/helmet-calibration-curve.png",
            alt: "Scatter plot of applied force against sensor reading, with a cubic spline fit rising steeply above a reading of about 700.",
            width: 454,
            height: 448,
          },
        ],
      },
      {
        id: "results",
        title: "Results",
        body: [
          "The majority of forces measured on any individual pad were between 0 and 5 N. However, some users exhibited pressure points with forces as high as 30 N. The contact force distribution is non-uniform across the interior of the helmet, with the largest force concentrated at the front.",
        ],
        media: [
          {
            id: "helmet-force-by-pad",
            orientation: "landscape",
            kind: "data",
            label: "05.4 — CONTACT FORCE BY PAD",
            subject: "Contact force distributions for each pad.",
            composition: "As published.",
            lighting: "As published.",
            purpose: "Show the result.",
            caption:
              "Contact force distributions for each pad for A no-chinstrap B user-comfort and C fixed-tension conditions. F=Front, FL=Front Left, BL=Back Left, B=Back, BR=Back Right, FR=Front Right, T=Top",
            src: "/images/helmet-contact-force-by-pad.png",
            alt: "Box plots of contact force by pad position for female and male volunteers, in three wearing configurations; the front pad carries the largest forces.",
            width: 970,
            height: 580,
            wide: true,
          },
        ],
      },
      {
        id: "publication",
        title: "Publication",
        body: [
          "Jennings, T., Tillman, A., Mukasa, D., Marchev, M., Müftü, S., Amini, R. Measurement and Assessment of Head-to-Helmet Contact Forces. Ann Biomed Eng 53, 946–955 (2025). https://doi.org/10.1007/s10439-025-03677-3",
          "Author contributions: Michael Marchev contributed toward methodology, validation, and investigation.",
          "Text and figures on this page are from the article and its supplementary material, published open access under a Creative Commons Attribution 4.0 International License (https://creativecommons.org/licenses/by/4.0/). Figures were resized.",
        ],
        links: [
          { label: "Read the paper — Springer", href: "https://link.springer.com/article/10.1007/s10439-025-03677-3" },
        ],
      },
    ],
    gallery: [],
    reflection: [],
  },
  {
    slug: "x-ray-scanner-lumafield",
    index: "06",
    title: "X-Ray Scanner for Lumafield",
    shortTitle: "X-Ray Scanner",
    organization: "Generate Product Development Studio / Lumafield project",
    role: "Mechanical Technical Lead",
    timeline: "Current / In Development",
    status: "In development",
    inDevelopment: true,
    theme: "light",
    categories: [
      "Technical Leadership",
      "Automation / Motion Systems",
      "Product Development",
      "Experimental Design",
    ],
    projectType: [
      "Technical Leadership",
      "Automation",
      "Precision Motion Systems",
      "Industrial Equipment",
      "Radiation-Safety Measurement",
      "Experimental Design",
    ],
    cardSummary:
      "Leading development of a 5-axis, 7 ft × 7 ft × 4 ft gantry system to automate shielding-verification scans around an industrial X-ray CT scanner, targeting 2–5 mm repeatability.",
    summary:
      "A gantry-based system that automatically sweeps a radiation sensor across Lumafield's CT scanners to detect leaks, replacing the current manual survey process.",
    tools: ["SOLIDWORKS", "Onshape", "FDM + SLA prototyping", "Linear motion components", "Excel"],
    team: "Mechanical, electrical and controls sub-teams at Generate, with Lumafield stakeholders",
    focus: [
      "Motion architecture",
      "Structural stiffness",
      "Repeatability",
      "Measurement coverage",
      "Serviceability",
    ],
    specs: [
      { label: "Gantry envelope", value: "≈ 7 ft × 7 ft × 4 ft" },
      { label: "Motorized axes", value: "5" },
      { label: "Positioning repeatability", value: "2–5 mm", target: true },
      { label: "Instrument", value: "Thermo Fisher RadEye G20 survey meter" },
      { label: "Subject", value: "Lumafield Neptune industrial X-ray CT scanner" },
      { label: "Scan coverage", value: "Automated paths across multiple scanner faces", target: true },
      { label: "Status", value: "Mechanical design and prototyping in progress" },
    ],
    drawing: "gantry-axonometric",
    hero: {
      id: "lumafield-hero",
      orientation: "panoramic",
      kind: "diagram",
      label: "06.0 — AXONOMETRIC",
      subject: "Axonometric drawing of the gantry.",
      composition: "As drawn.",
      lighting: "Line drawing.",
      purpose: "Show the system at scale.",
      caption:
        "Frame, scanner envelope, five-axis carriage and traced scan path, with a 5 ft 10 in figure for scale.",
    },
    card: {
      id: "lumafield-card",
      orientation: "panoramic",
      kind: "diagram",
      label: "06 — GANTRY",
      subject: "Axonometric drawing of the gantry.",
      composition: "As drawn.",
      lighting: "Line drawing.",
      purpose:
        "Frame, scanner envelope, five-axis carriage and traced scan path, with a 5 ft 10 in figure for scale.",
      caption:
        "Frame, scanner envelope, five-axis carriage and traced scan path, with a 5 ft 10 in figure for scale.",
    },
    sections: [
      {
        id: "summary",
        title: "Summary",
        body: [
          "Lumafield's CT machines must be checked for radiation leaks around their exterior panels to ensure operator and facility safety. Today, this is done by hand: an operator drags a handheld radiation sensor (a Thermo Scientific RadEye) slowly and carefully across every face of the machine, taking readings as they go. This manual sweep takes 30–60 minutes per survey and pulls a trained operator away from higher-value work for a task that is largely repetitive motion.",
          "Generate will design and build an automated gantry system that positions a radiation sensor along the exterior faces of Lumafield's CT scanners to replicate and replace the manual survey process.",
        ],
        note:
          "This project is a measurement tool. Nothing here suggests that Lumafield scanners are unsafe or inadequately shielded.",
      },
      {
        id: "role",
        title: "Role",
        body: [],
        list: [
          "Own the mechanical architecture and design direction.",
          "Translate the measurement task into functional requirements, motion envelopes, load cases and mechanical interfaces for the electrical and controls sub-teams.",
          "Direct gantry, axis, mechanism, frame and end-effector decisions.",
          "Run iterative design reviews and record the reasoning behind decisions.",
          "Coordinate mechanical work across the project team.",
        ],
      },
      {
        id: "prototype-demo",
        title: "Prototype Demo",
        body: [],
        list: [
          "Y-axis does not have any misalignment / racking",
          "RadEye sensor fixtured as end effector",
          "Gantry-style frame able to fit Neptune scanner inside",
        ],
      },
      {
        id: "mvs",
        title: "Minimum Viable Solution",
        body: [],
        list: [
          "Sensor can sweep along all four side faces while avoiding / scanning protruding features",
          "Limit switches mounted to prevent self-collision",
          "Cable routing to all axes and end effector to avoid snags during movement",
        ],
      },
      {
        id: "status",
        title: "Status",
        body: [
          "In development.",
          "Figures on this page are design targets. No repeatability, coverage or safety performance has been validated yet.",
        ],
      },
    ],
    gallery: [],
    reflection: [],
    confidentiality: "Proprietary information withheld.",
  },
];

/* --------------------------------------------------------------
   Derived helpers
   -------------------------------------------------------------- */

/**
 * Homepage selection, in display order. The first entry gets the large
 * `feature` spread, so this order is a curatorial choice and is deliberately
 * independent of archive order.
 */
export const featuredSlugs = [
  "stryker-fixture-designs",
  "sageware-textile-upcycling",
  "uplift-mobility-device",
  "x-ray-scanner-lumafield",
] as const;

export function getProject(slug: string): Project | undefined {
  return projects.find((p) => p.slug === slug);
}

export function getFeaturedProjects(): Project[] {
  return featuredSlugs
    .map((slug) => getProject(slug))
    .filter((p): p is Project => Boolean(p));
}

/** Next project in archive order, wrapping at the end. */
export function getNextProject(slug: string): Project {
  const i = projects.findIndex((p) => p.slug === slug);
  return projects[(i + 1) % projects.length];
}
